ublue-os/bazzite

.github/workflows/build.yml
I would like to bring this change into Bazzite, I'm experiencing the discover update loop.
Hopefully I'm interpreting what is needed correctly.
Thanks!
=> Maintain the Current OCI Version Label

.github/workflows/build.yml
Introduces Bazzite build support for Fedora 38
=> Add support for building against Fedora 38

Containerfile
See: https://github.com/ublue-os/nvidia/pull/112
=> Remove rpmfusion repo modifications

.github/workflows/release-please.yml, boot_menu.yml
This will generate a ISO upon merging a release
=> feat: Generate ISOs every release

deck/usr/share/ublue-os/just/custom.just, usr/share/ublue-os/just/custom.just
Adds just scripts to manage zram/deckswap
=> feat: Add just scripts to toggle zram/deckswap on/off and resize

system_files/deck/usr/bin/steamos-update
The existing system update check using skopeo has now been migrated over to ublue-update. This enables that check
=> feat(deck): Use new system update check

Containerfile, system_files/deck/usr/bin/plasma-autologin, system_files/deck/usr/lib/systemd/system/plasma-autologin.service, system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/usr/share/ublue-os/just/custom.just
- Remove cruft from gamescope-autologin
- Introduce plasma-autologin service
- Login to Plasma by default
=> feat(deck): Autologin to Plasma

system_files/deck/usr/share/ublue-os/just/custom.just, system_files/desktop/usr/share/ublue-os/just/custom.just
Fixes our nix configuration and adds some small QoL changes
=> fix: Address issues with just implementation

spec_files/jupiter-hw-support/user.patch, system_files/deck/usr/bin/gamescope-autologin, system_files/deck/usr/bin/plasma-autologin
This will always retrieve the first user created on the system and doesn't rely on there only being one user in the home directory
=> fix: Retrieve user by id

system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/usr/share/ublue-os/just/custom.just, system_files/desktop/etc/profile.d/guisu.sh, system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/usr/share/ublue-os/just/custom.just
This appears to be all that's left
=> fix: More yafti and just fixes

system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/usr/share/ublue-os/just/custom.just
Utility to add games from various clients to Steam and fetch respective artwork
=> feat(deck): Add BoilR

README.md
=> README adjustments for signed packages

Containerfile
Merge when [ublue-os/main#278](https://github.com/ublue-os/main/pull/278) is accepted
=> fix: Add needed akmods now that main no longer includes them by default

spec_files/jupiter-hw-support/jupiter-hw-support-btrfs.spec, spec_files/jupiter-hw-support/priv-write.patch
Fix from ChimeraOS: https://github.com/ChimeraOS/chimeraos/commit/fa7697fd9980dda59df5da52c4fbca0d24f405ca#diff-9a8d1fe67ff1847580d67f802d4e030c51fec313a023b1e51240cea9f3129006
=> fix(deck): Patch steamos-priv-write to address false failures

.github/workflows/build.yml
I want to put buildjet through it's paces, so I've set up nicer 4 core builders for bazzite for this development push. 
These should make things way faster for you., you may indulge yourselves! 😄
=> chore(ci): test out 4 core builders

Containerfile, README.md
Tied to https://github.com/ublue-os/akmods/pull/41
=> fix: Switch to SteamOS 3.5 steamdeck drivers.

system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml
Easy Effects provides an equalizer, compressor, limiter, and reverb tool for the manipulation of audio streams
=> feat(desktop): Add Easy Effects to installable utilities

Containerfile
Alternative option that only removes some unneeded RUN steps for comparison purposes.
=> Optimize Containerfile (v2)

Containerfile, system_files/desktop/gnome/etc/flatpak/remove, system_files/desktop/shared/usr/bin/ublue-flatpak-system-install
Adds support for a flatpak removal list that removes defined system flatpaks
=> fix: Support removing preinstalled system flatpaks

Containerfile
Allows editing when things go weird
=> chore: Copy yafti config to /etc

system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/bin/ublue-flatpak-system-install
Uses existing repo to install Flathub and addresses issue removing Fedora flatpakrepos
=> fix(flatpak): Locally install Flathub repo and fix Fedora repo removal

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/applications/yafti.desktop, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Provides clearer naming for users
=> chore(yafti): Rename to 'Bazzite Portal'

system_files/deck/shared/etc/wireplumber/bluetooth.lua.d/60-bluez-jupiter.lua
To avoid audio downgrade back to call quality. Props to Valve. License: https://gitlab.com/evlaV/steamos-customizations-jupiter/-/blob/master/COPYING.LGPL-2.1?ref_type=heads
=> Ignore microphones on headsets with microphones

Containerfile, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
This adds a just script that signs the current image and adds an entry for it in yafti which gets hidden afterwards.
=> feat: Sign Bazzite images in yafti

system_files/deck/shared/usr/share/ublue-os/just/custom.just
Fixed some of the nix installation and uninstallation part
Part of [THIS](https://github.com/ublue-os/bazzite/pull/219)
In this project we follow [Semantic PRs][1] and [Conventional Commits][2] to describe features and fixes we made. It would be nice if you did too. Not sure what this all means? Here are some [examples][3]. Did you already use this? Awesome, thanks again!
[1]: https://github.com/Ezard/semantic-prs
[2]: https://www.conventionalcommits.org/en/v1.0.0/#summary
[3]: https://www.conventionalcommits.org/en/v1.0.0/#examples
=> Update custom.just (this is for the deck part)

system_files/desktop/shared/usr/share/ublue-os/just/custom.just
Provides output in yafti... at the expense of the code looking ugly
=> fix(install-bazzite-arch): Use sh instead to get output in yafti

system_files/deck/shared/usr/bin/steamos-update
https://github.com/ChimeraOS/gamescope-session/commit/3cc0fbde3f1d018a700b74d49277baa7b4dfe89c
=> fix(steamos-update): fix updates not applying

README.md
...the device must use an AMD GPU at this time.
=> fix(readme): add a note about steam deck image that

Containerfile, spec_files/mesa/invariant.patch, spec_files/mesa/mesa.spec
=> chore: Override mesa-filesystem

.github/workflows/build.yml, Containerfile, boot_menu.yml
Thanks to:
https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#fedora-silverblue
=> feat: Add support for Surface devices

README.md
=> fix: add intel support for HTPC deck images

Containerfile, README.md, spec_files/gnome-randr-rust/LICENSE, spec_files/gnome-randr-rust/gnome-randr-rust.spec, system_files/deck/shared/usr/etc/xdg/autostart/discover_overlay.desktop
=> feat: Add gnome-randr

README.md, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
Depends on: https://github.com/ublue-os/main/pull/340
=> feat: Add OpenRazer to Just and Bazzite Portal

README.md
=> fix: outdated link to secure boot/nvidia information

Containerfile
=> fix(desktop): ublue-update.timer is a system service now

.github/workflows/build.yml, Containerfile
=> fix: Build Steam RPM in containerfile to avoid rpmfusion dependency issue

Containerfile
=> fix(steam): Try to fix copying Steam RPMs

Containerfile
=> fix(steam): Preserve Steam RPMs

Containerfile
=> fix(deck): Revert to copying Steam RPMs from GHCR hosted images

.github/workflows/build.yml, Containerfile
https://github.com/ublue-os/surface
=> fix: Surface images have moved

system_files/desktop/shared/usr/bin/bazzite-user-setup
Currently, this only gets written if the file exists. Create it when the file doesn't exist instead
=> fix(user-setup): Fix justfile creation

Containerfile
=> chore: Install steam separately without problematic repos

README.md
Not sure if you want this here, or at all.
=> feat: add link to FAQ to the README

README.md
=> feat: add table of contents section to README

system_files/shared/tmp/image-info.sh
=> chore(image-info): Use single cat instead of several echos

.github/workflows/build.yml, Containerfile, system_files/desktop/shared/usr/bin/bazzite-hardware-setup, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat: Enable builds without kmods

README.md
=> feat: Added showcase section and linked blog posts.

Containerfile
Merge me if the following lands:
https://github.com/ublue-os/main/pull/366
=> chore: Remove udev rules for Oversteer (These are included in main now)

README.md
=> docs: add information about xwaylandvideobridge

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
=> fix(hardware-setup): Set image flavor

Containerfile
=> fix: Avoid copying the akmods repo a 2nd time needlessly

Containerfile
=> fix: use new akmods:main-RELEASE tag structure

.github/workflows/build.yml
=> chore(ci): Maximize build space

.github/workflows/build.yml
=> chore(ci): Maximize space on builder

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Hi Team! 
Here is my PR! This adds the flatpak in the list of available games. This fixes https://github.com/ublue-os/bazzite/issues/380
Thanks, 
Noel Miller
=> feat(desktop & deck): Added XIV Launcher to list of available games

.github/workflows/build.yml, Containerfile
=> chore(ci): Move ASUS, Framework, and Surface images here

.github/workflows/build.yml
=> chore(ci): Switch to ublue-os fork of build space maximizer

README.md
even though it's at the top...
=> feat: add link to discussions

Containerfile, system_files/deck/shared/usr/bin/bazzite-autologin, system_files/deck/shared/usr/bin/steamos-session-select, system_files/desktop/shared/usr/bin/bazzite-hardware-setup
=> fix(HandyGCCS): Enable globally

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
=> feat(desktop): Add options to disable/enable watchdog

Containerfile, README.md, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat(nvidia): Switch to layered steam to avoid issues with 32-bit Nvidia libraries.

.github/workflows/build.yml, Containerfile, README.md, system_files/desktop/shared/usr/bin/bazzite-flatpak-manager, system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/silverblue/usr/etc/flatpak/install
=> feat(ci): Build images based on Fedora 39

Containerfile
=> fix(f39): Be explicit about arch in mesa replacement step

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
chore: moved Warehouse to this category.
feat: added Metadata Cleaner to Utilities category
fix: removed FAQ link at the end
=>  feat: Added "System Management" Category (deck)

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
chore: moved Warehouse to this category.
feat: added Metadata Cleaner to Utilities category
fix: removed FAQ link at the end
=> feat: Added "System Management" Category

Containerfile
=> fix(f39): Correct issue with mismatched curl version

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Under Utilities and System Tools
=>  feat: Add AppImage Pool to Bazzite Portal

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Under Utilities and System Tools.
=> feat(deck): Add AppImage Pool to Bazzite Portal

Containerfile
=> fix(deck): Add zenity and newt to fix issues with EmuDeck

system_files/desktop/shared/usr/share/ublue-os/just/30-distrobox.just
Replaces the identical Fedora distrobox checks with a hidden recipe making things a bit cleaner and making it easier to add new recipes that use the distrobox.
=> chore: Add cleaner fedora distrobox check.

.github/workflows/build.yml
Move build schedule back for official images
=> chore(ci): Build at 4:15 PM UTC

.github/workflows/build.yml
Enables testing and unstable branches. These are for testing new features before they are deployed to main
=> feat: Add support for a testing and unstable branch

Containerfile
=> fix: Restore evdi on F39

README.md
Flatseal, Warehouse, and Gear Lever.
=> feat(readme): Add application management features

Containerfile
Conflicts with ASUS kernel patches
=> fix(asus): Don't install evdi kmod

README.md
=> feat(readme): Add Features from Upstream

system_files/deck/shared/usr/share/ublue-os/just/30-distrobox.just, system_files/desktop/shared/usr/share/ublue-os/just/30-distrobox.just
=> feat: Added Alma Linux to justfile

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat(deck): Replace Website with Forums on Bazzite Portal

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat: Replace Website with Forums on Bazzite Portal

README.md
=> chore(readme): Link Waydroid guide

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat: Add documentation link to Bazzite Portal

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
=> feat(deck): Add documentation link to Bazzite Portal

README.md
=> feat(readme): Add link to announcements

.github/workflows/build.yml
Integrate our new [just syntax checker](https://github.com/ublue-os/just-action) into the build action.
=> feat: add just syntax checker

.github/workflows/build.yml
Allows the community to collaberate on changes that haven't made it into main yet.
=> chore(ci): Trigger builds for PRs to testing/unstable

system_files/deck/shared/usr/share/ublue-os/just/60-custom.just
=> fix(deck): Improve just scripts for bios handling

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
EOL runtime might be here to stay for too long.
=> chore: Remove Parsec from the Bazzite Portal

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Where it says "Forums & Documentation", changed to "Forums"
=> fix: Missing characters on Bazzite Portal

press_kit/README.md
=> chore: Discourse link in Press Kit README for newsletters

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Added Vivaldi Browser, Sonic Robo Blast 2 Kart, and Parallel Launcher (used with N64 ROM hacks)
=> feat: Add a few apps to yafti

.github/workflows/build.yml
This validates the base image via the public key generated by cosign.
=> feat(ci): Verify base image signature before building

Containerfile, system_files/desktop/shared/usr/lib/systemd/system/waydroid-workaround.service, system_files/desktop/shared/usr/lib/tmpfiles.d/waydroid-workaround.conf
=> fix: Correct labels on waydroid for selinux

README.md
=> chore(readme): Replace CoreCtrl with LACT

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
=> chore: update 60-custom.just

README.md
=> chore(readme): Formatted "Community" section

README.md
I linked the forum discussion thread and not the proper documentation format for the Dual Boot Guide and Misc. Doc.
=> fix(readme): Fix documentation links

README-SPA.md
Translation 100% complete, table of contents direct links haven't been fixed (yet).
=> feat(documentation): Translation of the readme to Spanish complete, sans fixing the table of contents links.

system_files/desktop/shared/usr/lib/systemd/system/sunshine-workaround.service, system_files/desktop/shared/usr/lib/tmpfiles.d/sunshine-workaround.conf
follow the symlink to get the actual binary.
=> fix: sunshine is a symlink

README-SPA.md
Added the new details from the updated english README, including the new secure boot section
=> chore(README): Updated translation with the latest additions to the english README

README-SPA.md
Added special thanks to SuperRiderTH for creating the new startup video for Game Mode
=> chore(README-ESP): Added special thanks to SuperRiderTH

README-ID.md
=> docs: add Indonesian language to README.md 

README-SPA.md
=> chore(readme-spa): Add Spanish FAQ Link

README-ID.md
=> docs: fix README-ID.md

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
prep for new tooling coming with https://github.com/ublue-os/config/pull/199
=> feat(just): Add changes to work with new tooling in ublue-os/config

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
A nice graphical interface for (distro/tool)box containers that is slightly simpler than Pods.
=> feat: Add BoxBuddy to Bazzite Portal

system_files/desktop/shared/usr/etc/profile.d/user-motd.sh, system_files/desktop/shared/usr/libexec/ublue-motd, system_files/desktop/shared/usr/share/ublue-os/motd/design/bazzite.md, system_files/desktop/shared/usr/share/ublue-os/motd/design/dark.json, system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-desktop-tips
=> feat: Add MOTD thanks to @bsherman and @castrojo

README.md
Also clarify Nvidia's proprietary drivers are only preinstalled on Nvidia images.
=> chore(readme): Link Bazzite-only documentation

system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
:pray: I hope the syntax is correct.
=> chore: Additional MOTD tips

README-SPA.md
Updated README-SPA with all changes commited since January 11th, fixed some spelling mistakes, removed the literal translation of "Game Mode".
=> chore(README): Updated README-SPA with all changes commited since January 11th

README.md
=> chore(readme): Clarify Intel Arc support

README-ID.md, README-SPA.md, README.md
=> chore(readme): Answer Overflow link to bazzite-help

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
switching to topgrade removed it
=> fix: add back ujust toggle-updates

README.md
=> chore(readme): Warning about Secure Boot for Deck users

README-SPA.md
=> chore(README): Updated translation to all changes up to Feb 14th

README.md
=> chore(readme): Link to bazzite for SEO

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Tested on my GPD Win 2 (8100y model)
=> fix(gpd): Correct screen rotation on the GPD Win 2

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/kinoite/usr/share/ublue-os/bazzite/flatpak/install, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/silverblue/usr/share/ublue-os/bazzite/flatpak/install
=> feat: Pre-install BoxBuddy

.github/workflows/build_iso.yml
Updates version to use latest and updated description
=> chore(ci): updated isogenerator to use latest

README-ID.md, README-SPA.md
=> chore(readme): Add download links to translations

system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md
This time I didn't use Github's editor so it shouldn't make a line
=> chore(motd): Shorten distrobox-export tip's link

.github/workflows/build_iso.yml
Fixing resolution issues with Steam Deck by appending anaconda command to grub
=> chore(ci): Add extra boot args feature to support steam deck

.github/workflows/build_iso.yml
=> chore(ci): update version with fix

README-SPA.md, README.md
=> chore(readme): Link CSS Loader Installer Guide

.github/workflows/build_iso.yml
This includes fixes for SECURE_BOOT_KEY_URL and allowing all languages to be available in the installer.
=> feat: Update isogenerator to latest version

.github/workflows/build.yml, .github/workflows/build_iso.yml
Updates the isogenerator action to use the latest versions.
Rather than hard-coding the output locations, use action outputs.
Run ISO builds when the workflow is updated.
=> chore: upgrade isogenerator action and add pull_request trigger

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
This will let users disable vfio if they have it enabled.
=> feat(just): add option to disable vfio

system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
...[Tips and Tricks documentation](https://universal-blue.discourse.group/docs?topic=574).
=> chore(motd): Fix documentation link for Tips and Tricks

README-SPA.md
Updated README-SPA.md to all commits done until March 1st
=> chore(README): Updated translation until March 1st

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
[Self-evident](https://yuzu-emu.org)
=> chore(yafti): Remove Citra and Yuzu

README-ID.md, README-SPA.md
This documentation has been removed.
=> chore(readme): Remove Misc. Doc. link for translations

system_files/deck/kinoite/usr/libexec/bazzite-rotation-fix
=> AIR plus rotation fix. same as Loki Max

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
IOMMU stays unsupported
Addresses #877
=> feat(just): Enable virtualization for deck hardware

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
=> fix(desktop): Ensure libvirt group exists in `/etc/group` so `usermod -aG libvirt $USER` can work

system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md
Adding a new line for the MOTD based on discussions in Discord, thank you all for being so supportive of our efforts!
=> feat: Add MOTD from Hit Save based on discussions in Discord

system_files/deck/shared/usr/bin/custom-device-pollrates.sh, system_files/deck/shared/usr/etc/custom-device-pollrates.conf, system_files/deck/shared/usr/lib/systemd/system-presets/99-custom-device-pollrates.preset, system_files/deck/shared/usr/lib/systemd/system/custom-device-pollrates.service, system_files/desktop/shared/usr/bin/custom-device-pollrates.sh, system_files/desktop/shared/usr/etc/custom-device-pollrates.conf, system_files/desktop/shared/usr/lib/systemd/system-presets/99-custom-device-pollrates.preset, system_files/desktop/shared/usr/lib/systemd/system/custom-device-pollrates.service
=> feat: Add Nobara USB Polling Rate Patch

README.md
=> fix(readme): Remove Dual Boot documentation

README.md
=> chore(readme): Add information about Handheld Wiki

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Fixes: https://github.com/ublue-os/bazzite/issues/986
=> feat: add command to support rebasing

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
This PR adds a small just action that setups a Ollama Container with the right GPU specific image on a users computer. The Ollama enables one to run local Large Language Models like Llama2 or similar.
=> feat(desktop): add an action to install ollama on a Bazzite system

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
ujust for disabling/enabling swipe gestures for gamescope-session
```
ujust disable-swipe-gestures
ujust enable-swipe-gestures
```
based on [disable-swipe-gestures.sh](https://github.com/aarron-lee/legion-go-tricks/blob/main/bazzite-disable-swipe-gestures.sh)
=> feat(ujust): add ujust for disabling/enabling swipe gestures

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-cdemu.just
I should have got them all now.
=> CDEmu just command fixes

.github/workflows/build.yml
I noticed this a few days ago and meant to fix it.
New issue reminded me.
Closes: #1028
=> fix(ci): set image version to match source

system_files/desktop/kinoite/usr/share/ublue-os/motd/tips/30-kde.md, system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md, system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md, system_files/desktop/silverblue/usr/share/ublue-os/motd/tips/30-gnome.md
=> chore(motd): Added new tips and removed outdated tips

.github/FUNDING.yml
if i missed anyone who has sponsors enabled, feel free to add yourself!
=> chore: add more people from the team to funding

Containerfile, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-cdemu.just
This should make this feature testable. On my end this works already perfectly fine now.
=> Final fixes for testing CDEmu

system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
chore(motd): remove punctuation to keep consistency with other tips
=> chore(motd): Add tip about bazzite-rollback-helper

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
=> fix(ujust): Add --or-update flag for Flatpak command

.vscode/tasks.json, Containerfile, Justfile, just_scripts/build-image.sh, just_scripts/build-iso-installer-main.sh, just_scripts/build-iso-makefile-patch, just_scripts/build-iso.sh, just_scripts/cleanup-dir.sh, just_scripts/cleanup-images.sh, just_scripts/container_mgr.sh, just_scripts/get-defaults.sh, just_scripts/list-images.sh, just_scripts/run-image.sh, just_scripts/run-iso.sh, just_scripts/sudoif.sh
=> feat(dev): add easy local iso and vscode integration

Containerfile, system_files/desktop/shared/usr/lib/systemd/system/brew-setup.service, system_files/desktop/shared/usr/lib/systemd/system/brew-update.service, system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.service
=> chore: use brew's installer

.github/workflows/build.yml, Containerfile, system_files/desktop/shared/usr/lib/systemd/system/brew-setup.service, system_files/overrides/usr/share/fish/vendor_conf.d/brew.fish
=> chore: compress brew on image

.github/workflows/build.yml
Also fix kernel signer on the new runners
=> chore(ci): Build with 24.04

system_files/desktop/shared/usr/lib/systemd/system/brew-update.service, system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.service
=> fix: brew auto upgrade services

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-cdemu.just
=> fix(ujust): setup-cdemu script failing to install cdemu

Containerfile, system_files/nvidia/shared/usr/etc/sddm.conf
Do not ship until 555/otherwise is stable.
=> feat(nvidia): Drop x11 session now that explicit sync is functioning

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Fightcade is a great platform for playing old fighting games. You can also play with other people online through their platform.
=> feat: add fightcade to yafti

README-zh-cn.md
=> docs: Add chinese language to README.md

README-zh-cn.md, README.md
=> docs: Add flags to select chinese languages.typo.

README.md
=> chore(readme): Clarify language for flag icons in ToC

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Unlike https://github.com/ublue-os/bazzite/pull/855 this isn't a major overhaul.
- Added the proper links to our docs.
- Replaced PinApp with Main Menu.
- Removed Parsec for supporting Ubuntu 18.04 exclusively so it has end of life runtimes.
- Renamed Steam Deck edition to Handheld/HTPC edition in description.
=> chore(yafti): very small changes

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-rmlint.just, system_files/desktop/shared/usr/share/ublue-os/just/rmlint-override.conf
Forgot to run sudo before creating files into /etc.
=> Permission fixes for rmlint script

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-rmlint.just
Missed my commit in flight right now :)
=> Last fix for copying the file correctly in place

system_files/desktop/shared/usr/share/ublue-os/just/rmlint-override.conf
Couple of bash quote potential issues fixes
=> Small script cleanup

spec_files/gamescope/deckhd.patch
fixes HDR in gamescope-session
=> chore: fixup deckhd patch

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
useful for debugging and testing if any controller issues for handhelds crop up and antheas require help testing.
=> feat: add hidden ujust to install hhd main branch locally

.github/workflows/build.yml
https://github.com/ublue-os/main/pull/589
https://github.com/ublue-os/hwe/pull/254/files
=> fix: adjust build schedule based on adjustments to main and hwe

Containerfile
=> fix: missing \

README-BR.md
Fixes the one typo I didn't catch in the original PR process. Sorry about that.
=> chore: Fix typo straggler in README-BR

README-BR.md, system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
This adds the missing kernel arguments for ONEXPLAYER F1
=> feat: kernel arguments for onexplayer f1

system_files/deck/shared/usr/libexec/bazzite-tdpfix
Will now fix the TDP on systems with multiple cards installed
=> feat(tdpfix): add detection for multiple cards

README.md
Link didn't go anywhere and it appeared before the Table of Contents section.  Language selection is hopefully self-explanatory to readers.
=> chore(readme): Remove language in ToC

system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite README.md
=> chore(docs): Fix README offline doc

system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Lenovo Legion Go.md
I may need to revise the whole handheld wiki eventually since there are so many fixes.
=> chore(docs): Remove experimental audio note

README-BR.md, README-FR.md, README-NL.md, README-SPA.md, README-zh-cn.md, README.md, system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/System Rollbacks.md
chore(docs): Fix grammatical error in Rollback Guide.
=> chore(readme): Remove outdated `-deck` information

.github/workflows/build.yml
=> chore(ci): Check Kernel is signed for Secureboot

Containerfile, system_files/desktop/shared/usr/libexec/containerbuild/cleanup.sh
=> chore(ci): use cache-mount and bind mounts

system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/GPD Handhelds.md
=> chore(docs): Updated GPD Win Max 2 information

system_files/desktop/shared/usr/share/ublue-os/topgrade.toml
=> fix: topgrade typo

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
=> fix(just): fix syntax for benchmark ujust

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Adds some minor changes to the help text for bazzite-rollback-helper
=> chore: minor updates to help text for bazzite-rollback-helper

docs/src/Bazzite_resources.md
Sorry for reporting this as a bug @Zeglius, but since we're going the route without emojis (which I am now going to be removing in the docs soon), I think it's best to keep this exclusive to the forum.
=> chore(docs): Delete Bazzite Resources

docs/src/SUMMARY.md
=> chore(docs): Shorten Steam Gaming Mode docs header

docs/src/Gaming/Hardware_compatibility_for_gaming.md
=> chore(docs): Fix broken Hardware Compat. Documentation

docs/src/SUMMARY.md
This is the last PR for the docs today I promise!!!
=> chore(docs): Add 'Fork An Image' Documentation

docs/src/SUMMARY.md
last PR for docs today pinky promise!!! also i'll look into the RGB rainbow goofy stuff later.
RGB was a mistake.
=> chore(docs): add new page 

docs/hooks/embed_youtube.py, docs/hooks/md_image_sizing.py, docs/mkdocs.yml, docs/utils/fetch_discourse_md.py
Fixes include:
- More consistent image URL fetching
- Prevent Youtube embedding inside links
- Move Youtube embedding step to `on_page_content`
- Size images on pair with Discourse ones
=> fix(docs): Several fixes for mkdocs

docs/theme_overrides/main.html
=> chore(docs): Fix note at the top

.github/workflows/deploy_docs.yml, docs/hooks/md_image_sizing.py
This fixes odd page segment duplicating inside themselves
=> fix(docs): Use a working match substitution in md_image_sizing hook

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
- Add a more informative message to install-resolve
- Bump up install-resolve SCRIPT_URL version
=> chore(just): Improve install-resolve ux

README.md
Will do translations at a later date.
=> chore(README-English): New documentation links

docs/src/index.md
This time merge this before conflicts happen.  Please and thank you @noelmiller @HikariKnight @KyleGospo
=> chore(docs): Minor improvements (again)

docs/src/Advanced/GNOME_Disks_Auto-Mount_Guide.md, docs/src/Advanced/KDE_Partition_Manager_Auto_Mount_Guide.md
This is not going to be on the index, but will be searchable for those who dare.  Also it's on the forum still and linked in "General Documentation" since it technically can apply to Bluefin/Aurora too.
=> chore(docs): Add auto-mount documentation (hidden)

docs/src/index.md
I want to work on an Update section next, but not today.  giving the acks a break.  thanks.
=> chore(docs): Hotfix

docs/src/Advanced/Reset_Forgotten_User_Password.md, docs/src/Advanced/Reset_User_Password.md, docs/src/index.md
Also added "handhelds" to the handheld list that have multiple handhelds.
=> chore(docs): Reset forgotten password name fix

docs/mkdocs.yml
=> chore(docs): wtf is a mkdocs!???!?!?

docs/src/Installing_and_Managing_Software/ujust.md
=> chore(docs): Fix issues with ujust documentation

docs/src/Advanced/Auto-Mounting_Secondary_Drives.md
=> chore(docs): Fix broken links in auto-mount guide

docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
Now that we're on Github... again.
=> chore(docs): Handheld Wiki can be edited properly

README.md
chore(readme): Organize social community links
Yes, there's still 1 more Bazzite Buzz but that will be it.
=> chore(readme): Remove references to Newsletters

README.md
I guess the link changed so here's the current one.
**Edit**: Added a link to: https://universal-blue.discourse.group/docs?topic=8
=> chore(readme): fix updates, rollback, and rebasing link

system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md, system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
=> chore(motd): Update to new documentation

docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md, docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md, docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md, docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md, docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
=> chore(docs): Handheld Wiki Updates

docs/src/Installing_and_Managing_Software/Distrobox.md
=> chore(docs): Distrobox Edits

docs/src/Advanced/Contributing_to_bazzite.md, docs/src/Advanced/Reset_Forgotten_User_Password.md, docs/src/Advanced/creating_custom_image.md, docs/src/Gaming/Common_gaming_issues.md, docs/src/Gaming/Managing_and_modding_games.md, docs/src/General/Installation_Guide/dual_boot_setup_guide.md, docs/src/General/reporting_bugs.md, docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md, docs/src/Installing_and_Managing_Software/Homebrew.md, docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md, docs/src/Installing_and_Managing_Software/ujust.md
There might be some other edits soon but these are the glaring ones.  PR or make an issue if you find other problems with the new documentation.
=> chore(docs): Final strides

docs/src/index.md
@castrojo @HikariKnight this link changed a little
=> chore(docs): fix links to updates rollback and rebasing

docs/src/General/Contributing_to_Bazzite.md
One has a capital B, the other is lower
=> chore(docs): Fix contributing guide (again)

docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
Update GPD docs with more info
=> chore(docs): update GPD documentation

docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
=> chore(docs): Link installation guide in Steam Deck wiki

docs/src/index.md
=> chore(docs): Fixing update doc 404 for real this time

README-BR.md
=> chore(docs): Update README-BR in line with 3.7.0

docs/src/index.md
=> chore(docs): Capital B for bazzite

docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md
=> chore(docs): No more numbered steps for update docs

docs/src/index.md
Flatpak still the best universal package format.  Eat your heart out!!!!
=> chore(docs): Give AppImage a description

docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
=> chore(docs): Steam Deck FAQ link fix

system_files/desktop/kinoite/usr/share/ublue-os/motd/tips/30-kde.md
I keep finding these... Should've forked this and made 1 big PR.
=> chore(motd): Link new documentation

system_files/desktop/shared/usr/bin/waydroid-launcher
Forgot about this one too.  Similar to https://github.com/ublue-os/bazzite/pull/1682/.
=> chore: Replace Discourse link with new docs page

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
Replaces the old Discourse version.
=> feat(just): Link new documentation

README.md
=> chore(readme): Use the "resources" doc over the Discourse link

.github/workflows/build.yml, .github/workflows/changelog.py, .github/workflows/generate_release.yml
Script is where it should, but action still needs work
=> feat: add automatically generated changelogs

.github/workflows/changelog.py
Ref is not testing it seems, but `refs/heads/testing`. Cut `/` and keep only testing.
=> fix(changelogs): Fix changelog ref error

Containerfile
see https://gitlab.com/setroubleshoot/setroubleshoot/-/issues/11
=> fix(selinux): fix setroubleshoot stacktraces

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
@HikariKnight This is for your stuff, so I'd figure you should look first.
=> chore: Replace old documentation link for ujust

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Didn't test it, but roll that baby in unstable and I will make sure it's ready for tomorrow!
=> Controverisal and opinionated Bazzite Portal changes

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
=> feat(just): add ujust for installing speaker firmware

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
I am going to try this on a `-deck` image in 10 minutes to see what I have to fix there.  I know DaVinci has to go sadly.
=> Fix issues with Bazzite Portal for Desktop images

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
=> chore(ujust): Fix -deck version of yafti configuration

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Add a '-y' flag to rebase subcommand, default to 'yes', and other tweaks
=> chore(bazzite-rollback-helper): Minor tweaks

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
I still don't understand why it doesn't launch now... :sweat_smile:
=> chore(yafti): Fix order for deck configuration

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> chore(yafti): Add visible password to desktop yaml config

.github/workflows/build.yml
=> fix: use digest for image signing instead

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
This should fix it.  Let me know if it doesn't though.
=> chore(yafti): Fix syntax error

system_files/desktop/shared/usr/bin/copr
=> fix: typo in copr wrapper

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Also fixed some other problems
=> chore(yafti): Remove Oversteer (-deck Edition)

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
=> chore(yafti): Remove Oversteer (Desktop Edition)

.github/workflows/changelog.py
Currently, we use the previous tag to generate the change log. This tag is found by finding all tags in all images and sorting them. This causes an issue in case there is a partial update and some images are pushed to the registry. In that case, we use a partial previous tag there is no changelog for, and it gets garbled.
Therefore, only use tags that exist in all images for the previous and current tag calculation
=> fix: prevent partial pushes causing partial changelogs

.github/workflows/clean.yml
=> feat(ci): clean up images older than 90 days

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Adds a small note in the bazzite-rollback-helper description.
=> chore: Note about rebasing between DEs with brh

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
=> fix(waydroid): Relabel /var/lib/waydroid on initial setup

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/bin/bazzite-steam
This adds verification to the video files, allowing them to be replaced if they have been changed or become corrupt.
Additionally, this also allows for video overrides to be disabled. A new just command was added to configure this.
=> feat(deck): Smart video handling, allow configuring.

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
=> fix(yafti): fix yafti pwfeedback toggle

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
Add more fallbacks and remove feature auto to avoid funnies
=> fix(gamescope): add more fallbacks, remove force fallback, use latest

system_files/desktop/shared/usr/bin/bazzite-steam
=> fix(deck): Fix overwriting Steam videos

README-BR.md
Should be up to date with the last two commits.
=> chore(docs): Remove TuneD, update fsync kernel and add a missing point on README-BR

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
improving layout and readability of 'ujust changelogs' and 'ujust changelogs-testing'
Before:
After:
=> feat: more readable ujust changelogs

Containerfile, build_files/dnf5-search
Replace part of the old workflow to dnf5.
This includes:
* Replace curl with dnf5 config-manager to add repos.
* Replace sed with dnf5 config-manager to enable/disable repos and set priority.
* etc...
=> feat(Containerfile): Migration to dnf5

Containerfile
=> chore(Containerfile): Add missing param on dnf5 swap

Containerfile
=> chore(Containerfile): Fix loop logic

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
=> fix(ujust): Remove case sensitivity from configure-watchdog

Containerfile
Exploratory PR to see what can be removed from our image thanks to DNF5
=> feat: Trim Lutris dependencies

Containerfile
Relates: ublue-os/akmods#295
This is expected to fail until the akmods PR is merged.
=> chore(ci): support combined akmods-kernel-cache in build

Containerfile
=> fix: add back snapper

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
=> fix(gamescope): fix rotation shader messing with input devices on intel

system_files/deck/shared/etc/security/rules.d/15-proton-nice.conf
https://gitlab.com/evlaV/steamos-customizations/-/commit/e63e60705eab5748e2da03baa379416fc941205c
=> fix(deck): import proton niceness setting from steamos

README-BR.md, README.md
=> chore: Update testing to have main's changes

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Docker inside a distrobox is just too cursed.
=> chore(just): Replace docker distrobox with a docker cli hooked to podman socket

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
=> feat(gamescope): add z13 display config

.github/workflows/build.yml
=> feat: Update kernel to 6.13.5-100

.github/workflows/build.yml
=> feat: Update kernel to 6.13.5-102

system_files/desktop/shared/usr/bin/scopebuddy
leftover from before the functionality changed
=> fix(scopebuddy): rename SCB_DEFAULT_ARGS to SCB_GAMESCOPE_ARGS

system_files/overrides/usr/bin/dnf
Now it will detect whenever we are running inside a container, and if so, redirect to dnf5
=> feat: Smart dnf wrapper

system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
=> feat(zone): add zotac gaming zone to supported devices

renovate.json
This will be a bit annoying due to it pinning everything but this is super important, we need to have consistent, pinned actions so we get rid of a few attack vectors.
https://docs.renovatebot.com/presets-config/#configbest-practices
=> ci: move to best-practices config for renovate

system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
=> fix: add MSI claw ids

Containerfile, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
It was causing issues, see https://www.reddit.com/r/Bazzite/s/0yV3nmTuDH 
Can be enabled with 'ujust enable-automounting' ~~or in yafti~~
=> feat: Add ujust enable/disable-automounting

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
=> fix(just): run restorecon for /var/lib/libvirt to fix selinux permissions

press_kit/README.md
Fixes a small grammatical error and replaces "Bazzite Buzz" newsletter link with the link to the social platform doc.
=> chore(readme): Remove duplicate 'about' in Press Kit README

system_files/deck/shared/usr/bin/steamos-update
Just needs a tiny bit of work on the stdout there, `systemctl start uupd.service` doesnt seem to be outputting anything to the stdout (thus the steamos-update logs)
=> feat(deck): use uupd on steamos-update script

Containerfile
=> feat: add incredibly important, essencial package for bazzite (glorpfetch)

Containerfile
=> chore: use main repo for nvidia-install.sh

Containerfile
Avoids terra repos disabling updates when down
=> fix: Ignore unavailabe repos

Containerfile
reverts ba35f773dcf850ae1dccb2876c782bcbd66ccc9e
https://github.com/ublue-os/packages/pull/394
=> chore: remove glorpfetch

.github/CODEOWNERS, .github/FUNDING.yml
I would humbly request to be added as a maintainer so I can be pinged about PRs and I would like to be added to funding document as well.
=> Add Noel as a Maintainer

Containerfile
The Flatpak is fully functional
Aurora did this as well:
see https://github.com/ublue-os/aurora/pull/398
Nobody will miss this
=> chore: remove kcharselect

system_files/desktop/shared/etc/distrobox/distrobox.ini, system_files/nvidia/shared/etc/distrobox/distrobox.ini
See https://github.com/ublue-os/toolboxes/pull/141
=> chore(distrobox): move to new arch-toolbox tag

.github/workflows/clean.yml
=> chore(ci): remove nokmods from cleanup

.github/workflows/clean.yml
=> fix(ci): remove more dead images

README-RU.md, README.md
=> Add russian lang readme

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
updates the ryzenadj max-performance ujust according to adolfo on Discord
=> fix: update max-performance ujust

.github/FUNDING.yml
=> chore: Remove nicknamenamenick from funding

Containerfile
Solves issue #2658
TODO: Remove this as soon as is fixed upstream
=> fix: Workaround for gnome file picker

Containerfile
Bump nvidia-install.sh to following commit:
https://github.com/ublue-os/main/commit/525e900bf8b3327e3738574a54089acb963a4d3e
This to add the version check
=> chore(nvidia): bump nvidia-install.sh

Containerfile
Far more consistent and user friendly than kde partition manager
=> feat: Use gnome-disk in all images

README-DE.md, README.md
- Added German README
- Updated English README to include German language selector
=> feat: Add German README translation and link

Containerfile
It clutters search, offers things which may not work and may be malicious. The desktop file approach is not a reliable solution.
=> feat: remove discover knewstuff backend

system_files/desktop/shared/usr/share/applications/yafti-go.desktop
=> feat: add categories to yafti-go

Containerfile, system_files/desktop/shared/usr/share/ublue-os/just/89-bazzite-mesa-git.just
`build-mesa-git` ujust command for a streamlined, user-friendly way to locally build Mesa from Git and use it as an optional graphics driver for games or other programs. 
```
═══════════════════════════════════════════════════════════════
Mesa Git installation not found
Run 'ujust build-mesa-git' to build from source.
═══════════════════════════════════════════════════════════════
Mesa Git Builder
Choose an action:
Build Mesa (from Git)     - Build Mesa from the latest git source.
Rebuild Mesa (force)      - Force a clean rebuild, even if already installed.
Cleanup Mesa build        - Remove Mesa Git installation and clean up containers.
Exit                      - Exit this menu.
Choose:                     
> Build Mesa (from Git)     
Rebuild Mesa (force)      
Cleanup Mesa build …
```
=> feat: ujust Mesa-git build and export for game overrides

spec_files/sunshine/LICENSE, spec_files/sunshine/sunshine.spec
This PR fixes the license for Sunshine, which uses GPLv3 not GPLv2. https://github.com/LizardByte/Sunshine?tab=GPL-3.0-1-ov-file#readme
=> chore(sunshine): fix license version

installer/titanoboa_hook_postrootfs.sh
Makes the limitations popup a more friendly welcome box.
=> chore(liveiso): More friendly Live ISO text

system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
=> fix: ensure fedora flatpak repo is disabled

system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just, system_files/desktop/shared/usr/share/yafti/yafti.yml
=> feat(ujust): Add disable-steamos-automount recipe

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
=> fix: respect decky permission security change in ujusts

system_files/overrides/usr/bin/dnf
This should allow the usage of commands like config-manager, list, etc.
=> fix(dnf): Passthrough all commands except install/uninstall

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-cdemu.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-rmlint.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-sunshine.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just, system_files/desktop/shared/usr/share/ublue-os/just/83-bazzite-audio.just, system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just, system_files/desktop/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/share/ublue-os/just/86-bazzite-windows.just, system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just, system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just, system_files/desktop/shared/usr/share/ublue-os/just/89-bazzite-mesa-git.just, system_files/desktop/shared/usr/share/ublue-os/just/90-bazzite-picker.just
=> chore: ujust groups

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
=> fix(openrgb): syntax error at ujust recipe

.github/workflows/changelog.py
=> fix: changelogs author

README-BR.md, README-DE.md, README-FR.md, README-ID.md, README-NL.md, README-RU.md, README-SPA.md, README-zh-cn.md, README.md
It seems the url has changed but I don't know if it's the right one
=> docs: Fixing sigstore url

system_files/desktop/shared/usr/share/ublue-os/just/83-bazzite-audio.just
Meant to include this in yesterday's PR, but forgot to. Extremely minute change.
=> chore(just): Provide more specific guidance
