ublue-os/bazzite

.github/workflows/build.yml
This mirrors [the upstream patch](https://github.com/ublue-os/nvidia/pull/79). The version tag fix I submitted previously did not work correctly. This commit changes to the better method now used in main and nvidia. I have tested this using images in my repo.
Thanks!
=> Pass Version Tag From Upstream Using Scopeo

etc/sddm.conf.d/virtualkbd.conf
Useful for devices with touchscreens like the Steam Deck. Provides a mode of input at login when a wired keyboard isn't available
=> Enable virtual keyboard at login

Containerfile, system_files/deck/usr/bin/steamos-update
This implements ublue-update in steamos-update, replacing the usage of rpm-ostree. This will allow for not only system updates, but flatpak updates and distrobox updates as well
=> feat(steamos-update): Initial support for Universal Blue updater

Containerfile, system_files/deck/etc/environment, system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml
Adds Nix to Yafti setup, along with VKBasalt and MangoHud flatpaks.
Additionally, fixes OBS flatpak plugin path, adds OBS flatpak vulkan layer, and via  new copr adds obs-vkcapture for native apps. New `etc/environment` on deck branch is due to deck being X11-only and therefore always needing it.
=> Adjust Yafti config to add Nix Package Manager and additional supporting Flatpaks

Containerfile, system_files/deck/usr/share/ublue-os/firstboot/yafti.yml
Current issues with the flatpak to consider this:
1. Issues with MangoHUD discovery in UI
2. Issues with vkBasalt discovery in UI
3. No LatencyFleX flatpak available
4. Need to use flatseal makes it hard for users new to Linux.
This change applies only to the deck branch, as desktop uses Lutris installed in distrobox already.
=> feat(deck): Layer Lutris to avoid common issues with the flatpak.

boot_menu.yml
=> fix(boot_menu): Correct bazzite-deck-nvidia label

system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/etc/profile.d/guisu.sh, system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/usr/share/ublue-os/just/custom.just
Corrects incorrect path in install-bazzite-arch, moves system configuration to the front of yafti, and introduces an alias for handling situations where we need the GUI to ask for escalated privledges (I.E. installing Nix)
=> fix: Address more just and yafti issues

system_files/deck/usr/bin/steamos-update
Universal Blue update isn't verbose unless something is logged or an exception is raised. Because of this, we can't just monitor its output and increment the progress bar. Instead, we need to wait for it to complete.
Since there isn't an entirely clean way of doing that, we'll just wait for the creation of '/tmp/update-check'
This also removes output from the updater to ensure that formatting stays consistent when the output is passed to Steam.
=> fix(steamos-update): Get progress bar working again

system_files/deck/usr/share/ublue-os/just/custom.just, system_files/desktop/usr/share/ublue-os/just/custom.just
This doesn't work as intended. Each command instantiates a new shell (disallowing indentation) making this a hurdle for readability, so remove it instead and continue explicitly defining the environment
This reverts commit 982be6c44fe65205ef6cbd59785a3883d1052ee2.
=> Revert "feat(just): Default to using bash"

spec_files/jupiter-hw-support/jupiter-hw-support-btrfs.spec, spec_files/jupiter-hw-support/jupiter-hw-support.spec, spec_files/jupiter-hw-support/power-button-handler.py
Moves power-button-handler into Bazzite and out of jupiter-hw-support, extends it with systemd-inhibit to block the power button only when it's running.
=> feat(deck): Handle power button

spec_files/jupiter-hw-support/power-button-handler.py
subprocess.call() improperly passes the inhibit function otherwise preventing the handler from ever starting in the first place
=> fix(power-button-handler): Rename 'inhibit' string to 'systemd-inhibit'

spec_files/jupiter-hw-support/power-button-handler.py
Dashes can't be used in variable names as they could be mistaken for subtraction
=> fix(power-button-handler): 'systemd-inhibit' -> 'systemd_inhibit'

Containerfile
This provides a terminal utility and UI for editing monitor parameters such as brightness, contrast, and color levels on supported monitors
=> feat: Include ddccontrol for controlling monitor params

system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/usr/share/ublue-os/just/custom.just, system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/usr/share/ublue-os/just/custom.just
Adds a script to just and entry to yafti setting the mount flags used by SteamOS BTRFS for all BTRFS drives in fstab
=> feat: Set SteamOS BTRFS mount flags for all BTRFS partitions

Containerfile
We have this marked as a dependency of jupiter-hw-support-btrfs here: https://github.com/ublue-os/bazzite/blob/71279c26b2d3583dc79f623d7503ec4af5c95da9/spec_files/jupiter-hw-support/jupiter-hw-support-btrfs.spec#L31
=> chore: Remove duplicate f3 installation from Containerfile

Containerfile
Test PR to see if this resolves our dependency issues, if it does we can continue with this based on:
1. Existing Steam Deck guides assume flatpak Lutris
2. Layered lutris installs wine as a layer, which is a waste of space on 64GB decks
3. Only feature gained is LatencyFleX, which does not outweigh 1 & 2.
=> chore: Remove layered lutris package

Containerfile, system_files/deck/etc/flatpak/install, system_files/deck/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/usr/share/ublue-os/just/custom.just, system_files/desktop/etc/flatpak/install, system_files/desktop/etc/systemd/system/flatpak-system-install.service, system_files/desktop/usr/bin/ublue-flatpak-system-install, system_files/desktop/usr/share/ublue-os/firstboot/yafti.yml
Inspired by and based on the work being done on Endlish-Oesque/Beyond, namely: https://github.com/ublue-os/beyond/pull/88
- Introduces script that installs system flatpaks automatically
- Moves system flatpaks out of yafti and defaults to user installation
- Adds Flathub as a system flatpakrepo by default
- Fixes errors/warnings from Flatpaks on desktop installations in yafti
This also moves Firefox to the web browser section instead of including it as a system package, letting users use the desktop shortcut to install it (matches SteamOS), select it in the web browser section, or select any other browser they are interested in
=> feat: Improve management of Flatpaks

Containerfile, system_files/deck/etc/flatpak/install, system_files/desktop/etc/flatpak/deck, system_files/desktop/usr/bin/ublue-flatpak-system-install
Installs all flatpaks without deploying them in the base image, and uses a configuration file to deploy Deck flatpaks
=> fix(deck): Address large image sizes due to layering Flatpak objects

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Unneeded now that it is included in the image
=> chore(yafti): Pull Firefox out of web browsers section

system_files/deck/silverblue/usr/bin/gnome-xorg-oneshot, system_files/deck/silverblue/usr/bin/steamos-session-select, system_files/deck/silverblue/usr/share/xsessions/gnome-xorg-oneshot.desktop, system_files/desktop/silverblue/usr/bin/gnome-autologin
Beneficial for Steam Deck as Steam Input doesn't function under Wayland on desktops yet, and beneficial for HTPCs as Nvidia doesn't handle Wayland quite well as of yet
=> fix(deck/autologin): Use GNOME on Xorg

Containerfile, system_files/deck/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/kinoite/etc/flatpak/install, system_files/desktop/shared/etc/profile.d/askpass.sh, system_files/desktop/shared/usr/bin/ublue-flatpak-system-install, system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/silverblue/etc/flatpak/install, system_files/desktop/silverblue/usr/bin/gnome-shell-extension-cl
These commits fix issues we are running into with conditional statements throughout the tree (primarily just, and yafti)
Yafti doesn't appear to support conditional statements at this time for package groups so I have created individual screens for those specialized packages that appear to work perfectly, albeit suggestions on how to better organize these screens are welcome
Invokations of rpm-ostree have been replaced with the usage of image identifiers that get written to `/etc/default/bazzite` at build time
This also fixes an issue where GNOME extensions weren't being installed in yafti, and removes a completely no-op toggle for GS Connect from yafti in Deck images (now that it is built in anyway), and adds askpass for GNOME images
=> fix: Issues with conditionals

system_files/deck/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Sourcing these doesn't seem to cut it as yafti doesn't acknowledge them so instead just use cat to obtain the file contents for the same result
=> fix(yafti): Revert to using grep and remove direct usage of image identifiers

system_files/deck/shared/usr/bin/gamescope-autologin
Addresses an issue where gamescope-autologin doesn't function correctly if this file exists after starting Steam. Appears isolated to GNOME. This doesn't cause issues with sessions switching as the file gets created by steamos-session-select regardless
=> fix: Avoid conflict between gamescope-autologin and session selector

Containerfile
We don't need these, and as a side effect this moves GNOME on Wayland to the top of SDDM
=> fix(gnome): Remove GNOME Classic sessions

Containerfile, system_files/deck/silverblue/usr/bin/gnome-autologin, system_files/desktop/silverblue/etc/gdm/custom.conf, system_files/desktop/silverblue/usr/bin/gnome-autologin
Restores GDM on desktop and implements GNOME autologin with GDM support. This allows users to use screen locking. Omitted from Steam Deck as there isn't a seemingly clean way to implement this for session switching. Will investigate in the future
=> feat(gnome): Use GDM on desktop

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/applications/yafti.desktop
Adds a desktop icon that utilizes the new '--force' option in Yafti to allow users to rerun it whenever they need to
=> fix: Add Yafti icon and only setup Steam desktop shortcuts under KDE

Containerfile
We had been doing this for desktop but not the Deck so the Deck would launch the right config at boot but not by the shortcut
=> fix(deck): Copy yafti config to /etc

system_files/deck/kinoite/usr/bin/startplasma-steamos-oneshot, system_files/deck/kinoite/usr/bin/steamos-session-select, system_files/deck/shared/etc/default/desktop-wayland, system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/deck/silverblue/usr/bin/gnome-session-oneshot, system_files/deck/silverblue/usr/bin/steamos-session-select, system_files/deck/silverblue/usr/share/wayland-sessions/gnome-session-oneshot.desktop
Adds support for toggling desktop Wayland sessions on and off for use with Steam's session switching. Off by default due to Steam Input not supporting Wayland on the desktop. To enable, run `sudo just --unstable _toggle_wayland`
=> feat(deck): Add (hidden) toggleable desktop Wayland session session support

Containerfile, system_files/deck/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh
This would forcefully open Steam every boot no matter whether or not users opted out of it in Steam
=> fix(deck): Autostart Steam using desktop shortcut rather than firstboot launcher

system_files/desktop/shared/usr/lib/systemd/user/bazzite-user-setup.service
Convert bazzite-user-setup to a simple service and use default target (multi-user target is only available to system services, the default target is used for user services)
=> fix(user-setup): Convert to simple service and use default target

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/bin/ublue-flatpak-system-install, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Moves Fedora's third party repository opt-out from Yafti to ublue-flatpak-system-install (this was actually previously no-op here and on Bluefin since it requires root), and moves user Flathub setup to the Bazzite user setup script
=> feat: Move Flatpak modifications to setup scripts

system_files/deck/shared/usr/share/ublue-os/just/custom.just
Resolves issues with 1 second being too short for Deck users to access GRUB
=> fix(deck): Extend GRUB hidden timeout to 3 seconds

.github/workflows/build.yml
Currently Nvidia GPUs don't support gamescope-session very well, making these images hard to justify. To be reverted when gamescope-session actually supports Nvidia cards well enough
=> chore(ci): Disable Bazzite Deck Nvidia images for now

Containerfile, system_files/desktop/shared/usr/bin/bazzite-user-setup
Removes the burden of updating the system from rpm-ostree and GNOME Software and places it on ublue-update
=> fix: Let Universal Blue Update handle automatic updates

system_files/deck/silverblue/usr/bin/gnome-autologin
=> fix(deck): Add Wayland support to GNOME autologin

system_files/desktop/silverblue/usr/share/applications/gnome-ssh-askpass.desktop
If initially opted into
Otherwise GNOME Shell (specifically under Wayland) will continuously prompt the user asking for permission to do so. This requires a desktop file be present so this adds one and hides it from the application menu
=> fix(GNOME): Allow gnome-ssh-askpass to inhibit shortcuts

.github/workflows/build.yml
Submits an image to the GitHub Container Registry on pull request approval, permitting approved pull requests to be tested before being merged.
Requires branch protection rule: 'Require approval of the most recent reviewable push'
This rule ensures that the state of a PR is reset after a new commit has been pushed to an open pull request.
=> chore(ci): Enable PR tagged images on pull request approval

.github/workflows/build.yml
Unlike the pull_request trigger, pull_request_review doesn't have an event number. So instead, pull it from the pull request
=> fix(ci): Use pull request number for PR tag instead of event number

system_files/deck/shared/usr/share/ublue-os/just/custom.just
GNOME users have long forgotten what a "~/Desktop" folder is, so I added a desktop entry for BoilR based on the Flatpak .desktop entry.
=> feat: added boilr .desktop entry

boot_menu.yml
Fixes improper resolution on the Steam Deck screen during installation
=> feat(boot_menu): Use new Deck kickstart to fix installation woes

.github/workflows/release-please.yml
This will ensure we are always using the latest version of isogenerator
=> chore(ci): Always use the latest version of isogenerator

.github/workflows/build.yml
Got this in main, overlooked it here. Didn't notice it as the prior fix still resulted in a proper push.
=> fix(ci): Yet another patch to ensure the PR number is always in the tag

Containerfile, README.md, spec_files/powerbuttond/LICENSE, spec_files/powerbuttond/powerbuttond.spec
Replaces previously used python solution.
See required supporting change in `gamescope-session` [here](https://github.com/KyleGospo/gamescope-session/commit/134eb89dfaaa30a028a05920f2449629d6fb36c1).
=> feat: Add new powerbuttond daemon from upstream Steam OS

system_files/deck/shared/usr/share/ublue-os/just/custom.just
Wanted to play TF2 on my Deck and discovered that it segfaults immediately on launch. I've encountered this issue before: this is because of Valve using an ancient version of tcmalloc for Source 1 games. So I made a [32-bit Debian container with latest tcmalloc installed which copies a fresher version of tcmalloc_minimal.so to the TF2 install folder](https://github.com/maisatanel/tcmalloc-hl2-fixer). Figured this would be useful as one of just scripts.
=> feat: Add a script for fixing tcmalloc for TF2

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
This fixes the just configure-waydroid script not properly cleaning itself up, and puts all of the dependencies into a virtual environment to further prevent any messiness.
=> Fix waydroid script

system_files/desktop/shared/usr/bin/bazzite-user-setup
Enable NTP by default. No one likes inaccurate clocks
=> feat(user-setup): Enable NTP by default

system_files/desktop/shared/usr/bin/bazzite-user-setup
Backs up old file just in case there are user recipes there. Fixes https://github.com/ublue-os/bazzite/issues/186
=> fix(user-setup): Ensure user always has working justfile

system_files/deck/shared/etc/systemd/system/batterylimit.service
It seems that you cannot use input redirection directly when running the command. Pass the command to bash instead seems to make it work correctly.
=> (fix) Make batterylimit.service work properly

system_files/desktop/shared/usr/bin/bazzite-hardware-setup, system_files/desktop/shared/usr/bin/ublue-flatpak-system-install, system_files/desktop/shared/usr/lib/systemd/system/bazzite-hardware-setup.service
Some scripts slow down the boot process when their services are enabled. The only fix for now is just to disable them, but with this PR it checks whether or not they already ran and skips them if so.
The problems is that if for some reason someone changes their hardware, those should be manually ran again by the user, so maybe there should be an option in Yafti or something like that for re-enabling these scripts.
=> fix(desktop): boot scripts slowdown

system_files/deck/shared/usr/bin/steamos-update
See: ChimeraOS/gamescope-session@2ef3a1f
Also increases the length and granularity of the progress bar
=> fix(steamos-update): Don't trigger updates during checks and increase progress bar granularity

.github/workflows/build.yml
Unfortunately, these only function for in org, and cause workflows from forks to fail
=> fix(build): Remove PR tagged images

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
This allows the signing process to be viewed in yafti's console
=> chore(just): Don't sign image in a subshell

system_files/desktop/shared/usr/lib/systemd/system/bazzite-hardware-setup.service
Hello! I've sent this PR for making sure the boot gets a bit faster by checking this file. But sadly I forgot that the condition check should be ran at the `[Unit]` key, not the `[Service]`, so this service wasn't running for anyone for a bit of time. I'm so so sorry for wasting your time. But at least here's a fix for it
=> fix(desktop): condition checked at proper section in bazzite-hardware-setup systemd service

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
If offline install media was used, use image identifiers for image signing. Otherwise, pull the current image information from rpm-ostree.
This addresses issues rebasing from tags other than tags using the Fedora version number.
=> fix(sign-image): Pull current image from rpm-ostree and fallback to image identifiers

system_files/deck/shared/etc/pipewire/99-input-denoising.conf, system_files/deck/shared/etc/wireplumber/main.lua.d/60-alsa-acp5x-config.lua, system_files/deck/shared/etc/wireplumber/main.lua.d/60-alsa-card0-config.lua, system_files/deck/shared/etc/wireplumber/main.lua.d/60-alsa-ps-controller-config.lua, system_files/deck/shared/var/lib/alsa/asound.state
~~This still needs an additional manual fix using alsamixer, pushing up microphone volume to 100, then running sudo alsactl store -F once to permanently store the configuration of the audio card, otherwise by default the microphone hardware volume will lower it again back to 52 (which is barely audible even cranked to 100 from the audio panel menu).~~
Fixed by adding the saved state as a default configuration file.
To my hears this feels almost identical to SteamOS now.
=> fix(deck): Fix stuttering volume in microphone

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
It is this here: https://github.com/solsticegamestudios/GModCEFCodecFix I put it into the justfile
=> Added GModCEFCodecFix  to justfile

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Currently, there doesn't seem to be confirmation that clicking accept on the consent screen actually did anything. Use a package screen instead to avoid confusion
=> fix(sign-image): Use package screen instead of consent screen

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
As soon as 2.0.0 gets a release, we can just fetch the latest version from GitHub, but until then...
=> chore(greenlight): Bump version to 2.0.0-beta12

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
Prevents rpm-ostree from failing when another transaction is in process by waiting for the current transaction to complete
=> fix(just): Wait for any existing transactions to complete before invoking rpm-ostree

Containerfile, README.md, spec_files/duperemove/duperemove.spec
feat: Explicitly use xxhash for duperemove and rmlint
=> chore: Add spec file for duperemove 0.12

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/bin/bazzite-hardware-setup, system_files/desktop/shared/usr/lib/systemd/system/bazzite-hardware-setup.service
Runs the hardware script every time the version of the script increments and every time the image is rebased (useful for transitions from main to Nvidia or Nvidia to main). Also disables Deck services on generic devices
=> chore(hardware-setup): Versioned/rebase checks, and disable Deck services on generic devices

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
Enable amdgpu on systems using the radeon driver. The arguments for Southern Islands and Sea Islands do not conflict so just enable both
Do not block this based on image flavor as some people may be using mixed GPU systems that have both an AMD and Nvidia card
=> feat(hardware-setup): Enable amdgpu on supported systems

boot_menu.yml
The only difference being that these use the standard kickstart file and exclude the resolution change from the installer
=> chore(boot_menu): Add entry for HTPCs

Containerfile, README.md, system_files/deck/shared/usr/bin/bazzite-discover-overlay, system_files/deck/shared/usr/etc/xdg/autostart/discover_overlay.desktop
Auto launches discover-overlay on desktop and gamemode if Wayland isn't in use  on the desktop and the Discord flatpak is installed.
Supporting change in gamescope-session: https://github.com/KyleGospo/gamescope-session/commit/3337d1a9a4c24f42bc95515358375ca164ff3751
=> feat(deck): Add discover overlay

system_files/desktop/shared/usr/share/ublue-os/just/custom.just
Allows just install-bazzite-arch to be used as a quick refresh for existing installs
=> chore(desktop): Delete bazzite-arch if it already exists in just command

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
For both deck and desktop, I've added `nix-store --optimse` to `clean-system` in the justfile
`nix-store --optimise` hardlinks identical files in the nix store. Here is some more information about what `nix-store --optimise` does: https://nixos.org/manual/nix/unstable/command-ref/nix-store/optimise.html
=> Added `nix-store --optimise` to `clean-system`

Containerfile, system_files/deck/shared/usr/bin/bazzite-autologin, system_files/deck/shared/usr/bin/return-to-gamemode, system_files/deck/shared/usr/etc/polkit-1/rules.d/return-to-gamemode.rules, system_files/deck/shared/usr/lib/systemd/system/return-to-gamemode.service
Fixes users not being to switch to gaming mode when they have desktop autologin toggled and should allow users to start gaming mode immediately after Steam has been updated instead of having to reboot after setup (although this should be done regardless)
Fixes: https://github.com/ublue-os/bazzite/issues/165
=> feat(deck): Add service to return to gaming mode

system_files/deck/shared/usr/share/ublue-os/just/custom.just, system_files/desktop/shared/usr/share/ublue-os/just/custom.just
Hello! I was setting up waydroid in my laptop and I thought that adding these waydroid utilities in just could be a nice addition :)
=> feat(just): add waydroid-related utilities

system_files/desktop/shared/usr/bin/bazzite-flatpak-manager
Per `flatpak list --help`, `--column` should be `--columns`
```
--columns=FIELD,…         What information to show
```
=> fix: Typo in bazzite-flatpak-manager

system_files/deck/shared/usr/bin/bazzite-autologin, system_files/deck/shared/usr/bin/return-to-gamemode, system_files/deck/shared/usr/bin/steamos-session-select, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/bin/bazzite-hardware-setup, system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/etc/profile.d/askpass.sh, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/30-distrobox.just, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just, system_files/shared/tmp/image-info.sh
Instead of the raw key being assigned, a key wrapped in quotations was incorrectly assigned
=> fix(image-info): Don't wrap identifiers in quotations

system_files/shared/tmp/image-info.sh
Explained over in https://github.com/ublue-os/bluefin/pull/518, but basically the system update script fails because it can't rebase without the prefix (`ostree-image-signed`)
=> fix(image info): use proper prefix in IMAGE_REF

Containerfile, README.md, system_files/deck/shared/usr/bin/bazzite-discover-overlay, system_files/deck/shared/usr/etc/default/discover-overlay
Only merge me once [this copr](https://copr.fedorainfracloud.org/coprs/mavit/discover-overlay/) has shipped [0.6.7](https://github.com/trigg/Discover/releases/tag/v0.6.7).
=> feat: Restore discover overlay support

system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Use current grub paths instead of depreciated F33 paths.
Also simplify detection by looking if /sys/firmware/efi exists, as BIOS systems don't have this directory.
=> fix: Correct hide/unhide grub just command

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
Based on user reports of nvidia kargs sometimes disappearing, let's just test them every boot and run less important stuff only on update
=> feat: Always check kargs

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
This adds the option to enable virtualization and vfio on the desktop image.
Enabling virtualization will:
* Install virt-manager, edk-ovmf2 and qemu as layered packages (distrobox is not feasable for this during my testing)
* Add 2 kargs for kvm to prevent a specific bluescreen in windows and to also prevent log and tty spam caused by said workaround.
Enabling VFIO will:
* enable the vfio kernel modules
* enable iommu in the kernel using the kargs appropriate for each cpu vendor
* make sure the vfio driver is loaded before gpu drivers
* disable vga output on any device bound to the vfio driver (this only applies to the host)
* display a message that support in regards to vfio will be very limited (this can be removed if preferable, however i know there is an extremely small amount of …
=> feat(desktop): Add option to enable virtualization and vfio

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Ran just enable-vfio on a new system and noticed awk command failed compared to the test system, saw that `print` had been replaced with `$print` at some point when writing and i have fixed that mistype.
Command has been tested on 2 systems now and it works each time (amd and intel check)
Also changed the script so that it will fail and exit if a cpu vendor for some reason is unknown or not detected, this will avoid situations where vfio will get "half enabled"
=> Enable virtualization

system_files/deck/shared/usr/share/ublue-os/just/30-distrobox.just
This forces Solaar to start in the background instead of opening each time the interface forcing people to close it each time.
=> Start Solaar minimized by default on login

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
This ensures that no watchdogs are draining the battery & affecting the performance on Steam Deck.
=> fix(deck): Block additional AMD watchdog kmod for Steam Deck

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Yafti currently installs Ardour when the user asks to install Krita, although this introduced me to Ardour (thanks!), I do think yafti should honor the users wishes and install Krita :smile: 
This should at least fix that.
=> fix: Make yafti install Krita instead of Ardour when user requests Krita

Containerfile
This restores kmods removed from Fedora 39
=> chore(f39): Restore kmods removed from main

Containerfile, system_files/desktop/shared/usr/lib/systemd/system/dev-hugepages1G.mount
This will enable auto mounting of hugepages with a pagesize of 1GB if the kernel argument `hugepagesz=1G` is present, which indicates the user has reserved hugepages with a pagesize of 1GB.
Hugepages with a pagesize of 1GB each is used for specialized VMs (like gaming VMs) to reduce latency due to memory page lookups for the VM, the default hugepages of 2MB each page has auto mounting enabled by default , however for special VMs like a gaming VM (should the user set one up), it would be favorable to auto mount it too as a pagesize of 2MB for a VM with 16GB ram would have `16777216` memory pages for the VM compared to the `16` you would get with 1GB hugepages.
Alternatively the we can set the feature disabled by default and instead be enabled with a just command, in which case i will …
=> feat: enable auto mounting of hugepages with 1GB pagesize if karg exists

system_files/desktop/shared/usr/etc/tmpfiles.d/10-looking-glass.conf, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
This adds the config for systemd to to generate the looking-glass shm file if libvirt requests it and also provide a just command to set the correct selinux file context for `/dev/shm/looking-glass`.
this will result in any libvirt VM started with
```xml
<shmem name="looking-glass">
<model type="ivshmem-plain"/>
<size unit="M">X</size>
</shmem>
```
inside the xml to auto create /dev/shm/looking-glass when needed.
the user will just have to run `just selinux-looking-glass` once on their system to permanently enable it.
If you do not know about looking-glass it is a kvm framebuffer relay for gpu passthrough.
Users will still have to download and compile the client with the same release as the host they installed in the VM from https://looking-glass.io/ for it to work, this will have to be …
=> feat: Looking glass shm OOB auto generation and support

.github/workflows/build.yml
This commit broke it - https://github.com/ublue-os/bazzite/commit/631423b360c69158382f17f20260ea05f2f8cc09
Duplicate overrides line 47.
=> fix: fix typo preventing 38 stable builds

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Flatpak Manager
Link: https://flathub.org/apps/io.github.flattool.Warehouse
=> feat: Add Warehouse to Bazzite Portal on Desktop images

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Flatpak Manager
Link: https://flathub.org/apps/io.github.flattool.Warehouse
=> feat: Add Warehouse to Bazzite Portal on Deck images

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
This adds a just command for enabling virtual audio channels for Game, Voice, Browser and Music.
This is useful for special use cases where you where you would want 2 separate controls for the audio (for example streaming, game audio control for you and game audio control for viewers/stream)
This can easily be achieved by splitting the audio off to one of these channels using something like qpwgraph, helvum or carla.
Users will still have to manually add the `Audio Output Capture` source in OBS to make use of this.
I found no way to replicate this using the obs-pipewire-audio-capture plugin from obs-studio-portable, if this is actually possible with that plugin then this PR can be ignored for that use case.
I also use this to listen to podcasts while streaming without sending the podcast …
=> feat: add virtual audio channels for special use cases

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Added a basic setup using the HeSuVi convolver file for Control Room 1 from https://github.com/ShanonPearce/ASH-Listening-Set just so there is something in the config.
If the user wants something like DTS, Atmos or OpenAL, they will have to hunt down the convolver wav files themselves as I am unsure about the legalities behind those files, so I figured it is better to just play it safe.
Also fixes missing comments above the virtual channels commands.
=> Feat: Add Virtual Surround 7.1 setup to just

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
There is no need for it since it will be applied automatically with initramfs LUKS workaround.
=> fix: Remove rd.luks.options=discard karg & use --append-if-missing for kargs

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/kinoite/usr/share/ublue-os/bazzite/flatpak/install, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/silverblue/usr/share/ublue-os/bazzite/flatpak/install
chore: Remove Warehouse and SaveDesktop from Bazzite Portal.
feat: Added Added [Resources](https://flathub.org/apps/net.nokyan.Resources) to Bazzite Portal.
feat: Added [Pika Backup](https://flathub.org/apps/org.gnome.World.PikaBackup) to Bazzite Portal.
fix: Removed System Applications in Bazzite Portal so users will not have to scroll anymore
chore: Moved PinApp and Save Desktop back to Utilities.
chore: Renamed Utilities to Utilities and System Tools in Bazzite Portal.
Since AppImages have a utility like Gear Lever, then there should be a utility for Flatpaks besides Flatseal preinstalled.
=> feat: Warehouse as preinstalled Flatpak.

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
There was a mistype in the remove-virtual-surround-71 command, this is corrected now.
=> fix: correct mistype in remove virtual surround command

Containerfile
The core for gamescope session was recently split away from Steam's session allowing it to be used for other sessions such as OpenGamepadUI's session independent of Steam's components.
=> chore: Install split gamescope session plus and steam packages

Containerfile
Dependencies pull in libwacom via libinput which conflicts with libwacom-surface
=> fix(surface-nvidia): Exclude OBS vkcapture

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Instead of linking to the Universal Blue homepage, it links to the Bazzite page on there.
=> feat: Add Bazzite's webpage from Universal Blue to Portal.

system_files/desktop/shared/usr/bin/bazzite-hardware-setup
It assures that this value will get properly configured for systems with ≥6.75GBs of RAM.
As this article shows, too low of a value is not good, and too high of a value is not good.
https://linuxhint.com/vm_min_free_kbytes_sysctl/
It is the only remaining non-applied ZRAM tweak from Pop-OS, which they included in their zram service.
https://github.com/pop-os/default-settings/commit/7fcad35#diff-964fc7d24025670fb776c01ef2943c84e637a3675c164696aebae19d86c8d46eR62
This checks if minimum-free ZRAM value is 1% of the maximum RAM of the current system, hence why this must go to the hardware service compared to simple sysctl config change.
=> fix: Add Minimum-free ZRAM configuration

system_files/deck/shared/usr/share/ublue-os/just/60-custom.just
- Prevents resize from writing multiple values to config files
- Instantly enables/disables deckswap
- Instantly resizes zram/deckswap
At this point, the only reboot required when it comes to memory tweaks, is to set/remove the zram karg.
=> feat(deck): Enhance and fix zram and deckswap scripts

Containerfile, README.md, system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/bin/bazzite-steam, system_files/desktop/shared/usr/bin/bazzite-user-setup, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/30-distrobox.just, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Drops the `bazzite-arch` pattern in favor of all images having steam layered into them. A lot has changed since our 1.0 release and while bazzite-arch has it's place, I think this makes more sense for the majority of our users now.
Additionally opens us up to supporting HDR via gamescope and vk_hdr_layer on desktop images.
Note that we will continue to maintain bazzite-arch as it continues to be a useful tool for numerous other distros, and can still be optionally used on bazzite if desired - IE: Mesa git, AMDGPU-Pro.
=> feat: Always layer Steam

Containerfile
=> chore: Use direct paths to bluez rpms due to rpm-ostree issue

system_files/deck/shared/usr/bin/bazzite-autologin, system_files/deck/shared/usr/bin/return-to-gamemode
In cases where the home directory path differs from the user name, it isn't enough to use a hard path that assumes the user's username is in it.
=> fix(autologin/return-to-gamemode): Don't assume path to home directory

system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/bin/bazzite-hardware-setup
Disables BIOS updates automatically and adds scriptlet for installing the DeckHD BIOS.
=> feat(deck): Implement support for the DeckHD

Containerfile
GOverlay (https://github.com/benjamimgois/goverlay)
It's a nice GUI for MangoHud, vkBasalt, and ReplaySorcery though.  In my testing in layering it to Bazzite, it complains MangoHud is missing, but it worked in my testing so I'm not sure why it does that. 
**EDIT:** Known issue in the latest stable.
It could also be placed in the Bazzite Portal as well instead of being preinstalled, and I can make a new PR for that.
=> feat: Preinstall GOverlay

Containerfile
chore: Remove redundant rpm-ostree invokation
=> chore: Don't fetch negativo17 fedora multimedia repo twice

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
The Forums already contain the documentation.  The user no longer has to scroll down to click the button that reboots their device.
=> chore: Remove documentation link in Bazzite Portal

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Parsec also has an EOL runtime, but [they are looking into it](https://github.com/flathub/com.parsecgaming.parsec/issues/37).
=> chore: Remove Stella due to EOL runtime in Bazzite Portal

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
`ujust enable-virtualization` will now tell the user to re-run the command after reboot to enable the libvirtd service.
the script now runs `rpm-ostree status | grep -A 4 "●" | grep "virt-manager"` to check if virt-manager is layered in the currently booted image and will run `sudo systemctl enable --now libvirtd` if virt-manager is layered.
=> feat: Enable libvirtd service if virt-manager layered

system_files/desktop/shared/usr/etc/tmpfiles.d/10-looking-glass.conf, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
Jilong on discord pointed out that the 10-looking-glass.conf file in /etc/tmpfiles.d will generate harmless but annoying log entries whenever qemu is not installed on the system.
This pull request moves the file into the selinux-looking-glass just recipe to avoid generating useless log entries about the lack of a qemu user.
=> chore: move 10-looking-glass.conf into just

system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
My previous pull request got merged a few seconds before a commit adding the missing shebang to the recipe got pushed, my bad.
This corrects it, still getting used to how just operates.
=> fix: add missing shebang to selinux-looking-glass

system_files/deck/shared/usr/share/ublue-os/just/60-custom.just, system_files/desktop/shared/usr/share/ublue-os/just/60-custom.just
The output of `ujust patch-source1-tcmalloc` gave this
```
echo 'Add the following as a launch option in Steam:'
Add the following as a launch option in Steam:
echo 'LD_PRELOAD=/usr/lib/libtcmalloc_and_profiler.so.4 %command%'
LD_PRELOAD=/usr/lib/libtcmalloc_and_profiler.so.4 %command%
echo "Delete libtcmalloc_minimal.so.x in the game's bin folder if present."
Delete libtcmalloc_minimal.so.x in the game's bin folder if present.
```
This should remove the echo part of the output so it just prints the message cleanly like this
```
Add the following as a launch option in Steam:
LD_PRELOAD=/usr/lib/libtcmalloc_and_profiler.so.4 %command%
Delete libtcmalloc_minimal.so.x in the game's bin folder if present.
```
=> fix(just): Fixed source1 patch 60-custom.just

system_files/desktop/silverblue/usr/etc/dconf/db/local.d/02-bazzite-global
It's a no-brainer to have this enabled out-of-the-box imo.
If someone knows how to apply this to KDE, let me know. I just learned that KDE doesn't have dconf equivalent.
=> feat(gnome): Enable num-lock by default

Containerfile
Python 3 is currently desynced between what's provided on the system, main Fedora repo, and updates.
=> fix: Use python3 (libs) from updates

.github/workflows/release-please.yml
Boolean output becomes a `string`, so needs to be checked against string value.
This should fix the :x: invalid merges to `main`.
=> fix(ci): build Release ISO condition

README.md
I consolidated the other Bazzite documentation into 1 page so that most of the documentation is now linked in the README. 
For now, it's called "Miscellaneous Documentation" for lack of a better term right now.  It's a little disorganized and lengthy, so I might fix that eventually.
I also added a link to Universal Blue's [Mastodon account](https://fosstodon.org/@UniversalBlue) so that reinforces to the general public that this is a Universal Blue image even more.
=> chore(readme): Added "Misc. Doc" and Ublue Mastodon

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
DNM until the dependent PR here is merged: 
https://github.com/ublue-os/config/pull/181
=> fix(yafti): Use new just shortcuts for nix/fleek

.github/workflows/build.yml, README-ID.md, README-SPA.md, README.md, system_files/deck/shared/usr/libexec/os-branch-select, system_files/shared/tmp/image-info.sh
The "stable" and "latest" tags are equivalent. Given "testing" and "unstable" tags are used, users may likewise figure that the current stable release uses the "stable" tag
=> feat(ci): Introduce a stable tag

Containerfile
closes #718 
This PR just adds the more stable rtl8814au driver back into the bazzite build instead of the unstable rtl88xxau driver. While this is removing driver capability for RTL8812AU/21AU cards, the driver has shown some instability with those as well. I'll take a look and see if there are some better options for those cards that we can include, for now if anyone needs them, there are old images, or it is easy to simply include both and install a modprobe blacklist which can be updated by the user.
=> fix(rtl8814au/rtl88xxau): package rtl8814au instead of rtl88xxau driver

Containerfile
This is to fix build issues I found this morning where glibc-headers and glibc-devel have dependency conflicts. I found this issue in my custom image which shares most of Bazzite’s Containerfile (minus a few things: https://github.com/noelmiller/isengard/actions/runs/7739690630/job/21103077663#step:6:1425)
=> fix: added glibc-headers and glibc-devel to override list

system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
This shortens the link so it doesn't get cut off in Prompt on KDE (and maybe GNOME)
=> chore: Fix Misc. Documentation link from cutting off in the terminal

README.md
It's not in the Portal anymore, but like Nix, it can be obtained with `ujust`
=> chore(readme): Remove mention of Brew in Portal

spec_files/gamescope/add_720p_var.patch, spec_files/gamescope/gamescope.spec
This patch allows for an environment variable, `GAMESCOPE_ENABLE_720P_RESTRICT`, to be set to re-renable the 720p restriction that Steam sets, ideal for setups such as mine on Steam Deck that have scripts to auto-adjust game config files based on what's visible to `XWAYLAND1`, also for games like DOOM Eternal where setting `+r_mode -2` forces the resolution to the highest available. Disabled by default, can be set in `/etc/environment`.
=> feat(gamescope): add env var for 720p patch

system_files/desktop/shared/etc/bazzite/initramfs/args.d/00-example.conf
Update the initramfs args example with link to documentation and information about using dracut conf files for including files in initramfs due to rpm-ostree limitation of only allowing the `--arg="-I /path/to/file"` argument only once.
=> chore: update initramfs args example with link to documentation

system_files/desktop/shared/usr/bin/waydroid-launcher
Currently the waydroid-launcher script never actually runs the `waydroid-fix-controllers` script while waydroid is running, only after waydroid is closed does it run
=> fix(waydroid): fix waydroid-launcher script

system_files/desktop/shared/usr/libexec/hardware/rotation-fix-hardware
For some reason the desktop gets rotated to the right on this laptop when on the deck image, this laptop has a landscape display and does not match any of our checks. Meaning it gets rotated by valve by accident?
This will correct it back to normal rotation.
reported by Crush in discord.
=> fix(deck): Correct rotation for Lenovo p14s gen2 in the deck image

system_files/desktop/silverblue/usr/share/ublue-os/bazzite/flatpak/install
[File Roller](https://wiki.gnome.org/Apps/FileRoller) would give to feature parity with KDE images because KDE ships [Ark](https://apps.kde.org/ark/).
=> feat(gnome): Add File Roller Archive Manager

system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Mangohud flatpak did not load my config. I found the override here:
https://github.com/ublue-os/bazzite/blob/5e18df5aa69dd5d45a17281124cb348b66b8aaec/system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager#L65
I thinks that's a typo because it should be `MangoHud` with a captital "H" and this should fix it. When I change it manually my MangoHud config is working again.
=> fix: mangohud config folder typo

.github/workflows/build_iso.yml
I think this may fix the mystery of the missing EXTRA_BOOT_ARGS in the ISO build.
=> chore(ci): add EXTRA_BOOT_ARGS to env for ISO build

system_files/desktop/shared/usr/libexec/hardware/rotation-fix-hardware
```
> cat /sys/devices/virtual/dmi/id/product_name
G1619-04
```
`G1619-04` aka GPD Win Max 2 (2022) has a landscape display. Everything (grub, bootsplash and gamescope) except the desktop is already in the correct orientation. 
Tested on the `bazzite-deck` image, running `/usr/libexec/bazzite/rotation-fix` puts the desktop in the correct orientation.
=> fix: correct orientation for GPD Win Max 2 (2022)

Containerfile
waydroid does not work with nvidia so the gpu selection script is not there on the nvidia image
=> fix: dont remove waydroid-choose-gpu on nvidia images

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
rpm-ostree initramfs is very temperamental.
=> fix: custom initramfs args actually get applied

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Added the option to add the user to the libvirt group so they do not have to provide the sudo password to use virt-manager
=> feat(just): add option to add user to libvirt group

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Another spot that doesn't get applied due to rpm-ostree initramfs being bizarre.
=> fix: make sure custom initramfs args are set

Containerfile, spec_files/jupiter-hw-support/priv-write.patch, system_files/deck/shared/usr/lib/systemd/system/bazzite-tdpfix.service, system_files/deck/shared/usr/libexec/bazzite-tdpfix
We do not know what causes a super small subset of GPUs to boot with sysfs writable on the deck images, but this will at least set the permissions back to 644 and reset the TDP at boot if it was messed with by gamescope-session and steam.
DNM before d3Xt3r tests and verifies that this works in `testing` as they have a system affected by this issue
=> feat(deck): add tdpfix for cards that has 15W TDP on boot due to writable sysfs on boot

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
This will also remove the old config if people run the command to change this.
=> feat(just): update recipe to edit tuned default profile using ppd.conf

README-SPA.md
Updated README-ESP to drop rmlint in all the mentions
=> chore: Drop rmlint due to being problematic.

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Until we move over to the KVMFR kernel module which gnif has confirmed is not picky with which version of Looking Glass the user is using , this warning message should be shown.
Once we have the kernel module included, we will change the option to add the config based on
https://looking-glass.io/docs/B7-rc1/ivshmem_kvmfr/
=> feat(just): add warning message for looking-glass shm creation.

.github/workflows/build_iso.yml
Upload artifact name has a variable that was wrong. This PR fixes it.
=> chore(ci): fix up name of iso artifact in testing

.github/workflows/build_iso.yml
This will test using the main branch to fix extra boot params issue when building ISO. I will ask Jason to do a release once I have tested this change in cosmic, bazzite, and bluefin.
=> chore(ci): test main branch to fix extra boot params

spec_files/gamescope/gamescope.spec, spec_files/gamescope/loki.patch
This needs gamescope-session-plus edit in device-quirks to works, removing the panel being forced as external
If not it does nothing, so no harm done.
=> chore: Add patch for Ayn Loki refresh rates in gamescope

.github/workflows/build_iso.yml
was an oversight when updating action
=> chore(ci): install using apt since no longer using a container

system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md
I plan to merge the dual boot documentation with the installation guide and re-arrange some of it especially since handheld usage is becoming increasingly popular.
=> chore: Remove dual boot documentation in MOTD

system_files/deck/kinoite/usr/libexec/bazzite-rotation-fix
=> Mini Pro rotation fix.  Same as Loki max and AIR

spec_files/gamescope/3.13.16.9-splitgate.patch, spec_files/gamescope/gamescope.spec
the 3.13.16.9 upstream gamescope tag contains a fix for Splitgate crash on exit. add these commits as a patch so that it doesn't do that and we're all happy again.
=> fix(gamescope): add 3.13.16.9 splitgate crash fix

system_files/deck/kinoite/usr/libexec/bazzite-rotation-fix
Reverts ublue-os/bazzite#962
Didn't seem to work in the `:testing` channel for one user.   Lower priority anyways as the handheld has no internal audio functioning.
=> chore: Revert "Mini Pro rotation fix.  Same as Loki max and AIR"

system_files/deck/kinoite/usr/libexec/bazzite-rotation-fix
ayaneo slide rotation fix. Same as Mini Pro, Loki max and AIR
=> fix(ayaneo slide): flipping upside down in desktop mode

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Correctly applies vfio after recent initramfs changes, also fixes the actions by removing `enable` and `disable` as actions and instead replace them with `virt-on` and `virt-off`
=> fix: Correctly apply vfio after initramfs changes

spec_files/ds-inhibit/10-modprobe-ds.conf, spec_files/ds-inhibit/ds-inhibit.spec
ds-inhibit on upstream has issues with the first connect of PlayStation controllers, where the touchpads are not hooked correctly and therefore don't correctly interact with steam input. work around by using modules-load.d to autoload hid-playstation on boot.
=> fix(ds-inhibit): autoload hid-playstation to avoid hook conflicts

Containerfile
This is required to be compatible with updates to akmods which drop the nvidia version tag from `akmods-nvidia` images.
Relates: https://github.com/ublue-os/akmods/pull/171
=> chore: drop nvidia version from akmods-nvidia

.github/workflows/build.yml, Containerfile, system_files/desktop/shared/usr/libexec/containerbuild/build-initramfs, system_files/desktop/shared/usr/libexec/containerbuild/image-info
There is now a single place in the build workflow where `kernel_version`
can be specified to pull the desired `akmods` image (assuming it was built 
and tagged correctly) which also impacts the rest of the workflow and
the Containerfile logic for replacing kernel, or not replacing kernel.
This is the new `kernel_flavor` include in the matrix configuration.
Current valid values would be: main, fsync, or fsync-lts
other included changes:
- pre-pull source images before building (makes building more reliable)
- add retry action for image push/pulls (makes building more reliable)
- rename FEDORA_MAJOR_VERSION/major_version to FEDORA_VERSION/fedora_version
(in matrix vars) (this is easier to read)
- read kernel version from akmods image and use to populate `ostree.linux`
label on the built …
=> refactor(ci): retry image pull/push, fix oci labels

.github/workflows/build.yml
fix use of cosign-action/sign breaking due to wrapping the push step in a retry action
=> fix(ci): extract digest output from retry action

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
This is a basic helper script to make it easier to manage rollbacks on bazzite.
```
====== Bazzite Rollback Helper Util ======
This Tool aims to help with rollbacks and rebases
Usage: bazzite-rollback-helper [OPTION] [ARGUMENT]
Options:
list      List available Bazzite images, Default is "stable"
rollback  Rolls back to previously installed Bazzite image. alias for "rpm-ostree rollback"
current   Show currently active Bazzite image
rebase    Rebase/rollback to specified Bazzite image, Default is bazzite-deck:stable
Examples:
bazzite-rollback-helper list stable
bazzite-rollback-helper rollback
bazzite-rollback-helper current
bazzite-rollback-helper rebase bazzite-deck:39-20240315
bazzite-rollback-helper rebase bazzite-deck:stable
bazzite-rollback-helper rebase stable
For more help, visit …
```
=> feat: add bazzite-rollback-helper util

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
This is a draft until I have done proper testing on my system and should finalize us moving over to the [kvmfr module](https://looking-glass.io/docs/rc/ivshmem_kvmfr/).
The module has been compiled using the makefile from [LookingGlass/module](https://github.com/gnif/LookingGlass/tree/master/module) and is not modified by us in any way, and is currently pinned to [B7-rc1](https://github.com/gnif/LookingGlass/releases/tag/B7-rc1) until a new RC release is made.
The package is just a dkms to akmod conversion in order to work with atomic desktops (essentially compile the module and put it in the right place and tell akmods to rebuild with kernel), no changes has been made to the upstream code.
Users still have to [manually compile the looking-glass-client using upstream …
=> feat: Deprecate looking-glass shm in favor of kvmfr module

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Don't look for compress=zstd as user may want to set this. Instead, set a flag so filesystem options are set on first boot instead.
=> fix: /etc/fstab adjustment condition

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
fixing a funny typo :sweat_smile:
=> fix: no longer tell people to configure grub when showing virtualization helptext

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
New GPD Win Mini 2024 with Ryzen 8x40U have horizontal screens same as Ally
=> fix(deck): don't do screen rotation on GPD Win Mini 2024

spec_files/steamdeck-kde-presets/steamdeck-kde-presets.spec, spec_files/steamdeck-kde-presets/wayland-remove-env.patch
To enable IBus in wayland session, it is necessary to remove environment variable  `QT_IM_MODULE` and `GTK_IM_MODULE`. The proper method to make ibus work is setting virtual keyboard to "IBus Wayland".
=> fix(kde): Remove `QT_IM_MODULE` and `GTK_IM_MODULE` for IBus in wayland

system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
chore: Rename Steam game mode video to Steam Big Picture Mode video for Desktop images
=> feat(desktop): EmuDeck added to Desktop images

system_files/nvidia/shared/usr/etc/sddm.conf
Maybe soon the proprietary Nvidia drivers can run a Wayland session without exploding into giblets.
=> feat(nvidia): Default to x11 again

.github/pull_request_template.md
=> fix: update link to universal blue contributing guide in PR template

system_files/deck/silverblue/usr/etc/environment, system_files/desktop/silverblue/usr/etc/environment
This is no longer needed for VRR in v40+ and it breaks direct scanout.
=> chore(gnome): remove MUTTER_DEBUG_FORCE_KMS_MODE

system_files/deck/shared/usr/lib/systemd/system/batterylimit.service
Based on my testing with my Deck LCD on 0131 it seems that it randomly loses the setting after sleep/reboot/shutdown.
Run this command after each possible systemd stage to force it to leave this applied correctly. Tested locally.
=> hotfix: batteryservice on latest bioses

system_files/desktop/shared/usr/lib/systemd/system/btrfs-dedup@.service
I think since I reported #959 `sqlite` still errors in the `btrfs-dedup@.service`:
https://github.com/ublue-os/bazzite/blob/b5f4b6d179993d39c5f607958a91f2a330aa3ac6/system_files/desktop/shared/usr/lib/systemd/system/btrfs-dedup%40.service#L13
```sh
ei 09 13:39:31 desktop-bazzite systemd[1]: Starting btrfs-dedup@var-home.service - Btrfs deduplication on /var/home...
mei 09 13:39:59 desktop-bazzite compsize[18933]: Processed 725459 files, 4077370 regular extents (4581627 refs), 322845 inline.
mei 09 13:39:59 desktop-bazzite compsize[18933]: Type       Perc     Disk Usage   Uncompressed Referenced
mei 09 13:39:59 desktop-bazzite compsize[18933]: TOTAL       85%      727G         847G         895G
mei 09 13:39:59 desktop-bazzite compsize[18933]: none       100%      573G         573G …
```
=> fix(desktop): sqlite column error in btrfs-dedup service

system_files/desktop/shared/usr/lib/udev/rules.d/99-cec-bluetooth.rules
Added a new udev rule which is triggered when a Bluetooth device is connected. It calls `/usr/bin/cec-control onboot`, same as `cec-onboot.service`, should set the TV's input source to Bazzite. Useful when you just grab the controller and turn it on to start gaming.
=> feat: Trigger CEC onboot on Bluetooth device connection

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Changed a '>' to a '>=' so that `ujust ptyxis-transparency` can set the transparency to 1, i.e. fully opaque.
=> fix(ujust): allow setting Ptyxis transparency to 1 (fully opaque)

Containerfile, system_files/desktop/shared/usr/lib/systemd/system/brew-dir-fix.service, system_files/desktop/shared/usr/lib/systemd/system/brew-update.service, system_files/desktop/shared/usr/lib/systemd/system/brew-update.timer, system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.service, system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.timer, system_files/desktop/shared/usr/lib/tmpfiles.d/homebrew.conf
Brew was being copied into the wrong directory. The directory `/var/home/linuxbrew` was missing and causing things to be copied to `/var/home/linuxbrew` and not `/var/home/linuxbrew/.linuxbrew`.
This makes sure it is in the correct spot. This is handled via a oneshot service. The service checks if `/var/home/linuxbrew/Homebrew` exists and if `/var/home/linuxbrew/.linuxbrew/Homebrew` doesn't exist. If that's the case, it mv's the dir to /tmp, makes the correct `/home/linuxbrew/.linuxbrew` directory and mv's everything back underneath the newly created dir.
The service is only needed for a few weeks and can then be removed.
=> fix: correct brew directory.

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
* Add a new ujust recipe `install-boxtron` for installing [boxtron](https://github.com/dreamer/boxtron) for playing retro DOS 
pc steam games. 
* Resolves #1142
=> feat(ujust): add new recipe 'install-boxtron'

spec_files/mesa/mesa.spec
Fixing up some issues leftover from #1082 
- Reverting back to Fedora packages for `proc-macro2` and `syn` (the recent addition of `spec_files/mesa/mesa-28923.patch` should fix that issue)
- Reintroduce `%rewrite_wrap_file` - that does seem to fix an issue where meson cannot find the `syn` package
=> chore(mesa): remove rpmbuild/meson workarounds in mesa.spec

system_files/desktop/shared/usr/bin/bazzite-steam
Using '>' instead of '-gt' always returns true (as '>' is not valid with 'test'), adding the flag '-cef-disable-gpu' regardless of the device using a dGPU.
=> fix: correct bash if statement for dGPU detection

system_files/desktop/shared/usr/bin/waydroid-launcher, system_files/desktop/shared/usr/libexec/waydroid-fix-controllers
This PR ensures waydroid-launcher is able to pass through the arguments given to `waydroid-launcher`. This means waydroid-launcher can be used for more than just launching the full UI, such as running a single app. Thus, this means additional desktop entries could be created running individual apps, which can then be added to Game Mode.
This also fixes a small bug in `waydroid-fix-controller`. The globbing for some reason doesn't work properly, thus it doesn't seem to work well. This uses `tee` instead to pipe the output using sudo.
=> feat(waydroid): pass arguments for waydroid-launcher through to waydroid

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Currently, running `ujust install-opentabletdriver` when you don't already have an Arch distrobox will create one and try to install opentabletdriver. This will fail because the repos are out of sync and it can't locate the files needed. This should fix that by running `paru -Syu --noconfirm` before trying to install opentabletdriver.
=> fix(ujust): sync arch packages before installing opentabletdriver

system_files/desktop/shared/usr/lib/systemd/system/sunshine-workaround.service
fix(sunshine): sunshine-workaround missing closing quote in ExecStartPre line preventing proper execution. See #1204
=> fix(sunshine): fix systemd file for missing closing quote

spec_files/mesa/mesa.spec
Bump to latest mesa patch release (24.1.1)
COPR build to validate: https://copr.fedorainfracloud.org/coprs/trouter/bazzite-multilib/build/7610825/
(Build is in progress at time of opening this PR; check it's green in COPR before merging)
=> chore: bump mesa to 24.1.1

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
This is replaced by hhd overlay which is activated by double/triple pressing the QAM button (or holding it on handhelds that support the hold action)
This also moves the hidden `_hhd-dev` recipe to only be available in the deck image.
=> feat: Remove decky hhd plugin, replaced by built in hhd overlay

system_files/desktop/shared/usr/libexec/bazzite-powersave
the default is to enable power-saver mode when run and that always worked and was the point of the script, which is why this never got caught before now.
Script was made basically because the dbus calls to do this are horrible for both DEs
`/usr/libexec/bazzite-powersave` sets PPD profile to `power-saver` for gnome and kde (will detect DE)
`/usr/libexec/bazzite-powersave 0` will now correctly set PPD profile to `balanced`
=> fix(bazzite-powersave): make arg to set PPD to balance work

Containerfile
Wine is in wow64 mode which seems to often not work and seemed to cause some people trouble with lutris, by default  Fedora sets wine and wine preloader to be 32 bit executables
=> fix(wine):Match Fedora wine's configuration

Containerfile
ydotool functions as an autoclicker, of which Bazzite is currently missing
=> feat: Add ydotool

Containerfile
Add `fcitx5-chinese-addons` package under fcitx5-mozc to enable advanced input method for Chinese users. (Shuangpin, Wubi..)
Fcitx5 is a widely used input method framework among Chinese users. It supports various input methods such as Shuangpin and Wubi, which significantly speed up the typing process. Shuangpin allows users to input Chinese characters with just two keystrokes, while Wubi uses stroke-based inputs.
To enable these input methods, an additional Fcitx5 package needs to be layered, similar to `fcitx5-mozc`
Once the package is layered, the package should function correctly.
+ [Containerfile:488]
=> feat(fcitx5): Add advanced Chinese input method `fcitx5-chinese-addons`

system_files/desktop/shared/usr/lib/systemd/system/sunshine-workaround.service
current systemd unit seems to not like the sunshine symlink
hopefully this should fix it (it seems to have done it for me)
=> fix: update sunshine workaround to handle symlinks

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Seems like PR #1237  did not reliably detect if virt-manager was installed on all images, so i changed it to a simple `rpm -q` check to fix it.
=> fix(just): correctly detect if virt-manager is installed

system_files/deck/shared/usr/libexec/bazzite-sdl-gpu-warn, system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh
Only triggers if `/usr/libexec/bazzite-sdl-gpu-warn` exists (it only exists on handheld images)
also triggers on any gpus defined in `/usr/libexec/gamescope-sdl-workaround` so the text is kept generic.
Anomaly: Polaris users already on the `-deck` image will see the warning next time they go into desktop mode, they can accept it, click ok and move on with their day and not see it again.
=> feat: add firstboot warning to users with polaris gpus about gamemode fix

system_files/deck/kinoite/usr/etc/xdg/kcm-about-distrorc
For consistency purposes, it changes the `-deck` image to be known as the Handheld/HTPC variant since we now support more handhelds outside of the Steam Deck.
=> chore(deck): Change variant name to "Handheld & HTPC"

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Fixes plugins that do not use environment variables... 
Is only created if users home is not `/home/deck` and there is not already a working symlink in place
=> feat(just): make setup-decky create /home/deck symlink on install

system_files/desktop/shared/usr/lib/tmpfiles.d/setroubleshoot-workaround.conf
setroubleshootd.service failed if `/var/lib/setroubleshoot` didn't exist owned by `setroubleshoot:setroubleshoot`
=> fix: setroubleshoot with no access to /var/lib/setroubleshoot

system_files/overrides/usr/share/fish/functions/fish_prompt.fish
Modified default fish shell prompt to indicate if a user is inside a container with a box icon and the container name, similar to how bash looks inside a distrobox container. Not sure if there was a better way to do this, but it works!
Here's a comparison of the stock fish shell vs when I'm in a container I made for LLM stuff.
=> feat: Container indicator for fish shell

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
The GPD Win Mini 2024 edition has a native landscape display. This means it doesn't need to be rotated like the 2023 edition.
They recently released a 7640U version, which is not being detected correctly. This patch correctly identifies this version and omits the rotation.
```
root@bazzite:~# /usr/libexec/bazzite-hardware-setup
Current kargs: rhgb quiet root=UUID=b6987ce0-6120-4483-a54f-d5fcb507ee0c rootflags=subvol=root rw iomem=relaxed bluetooth.disable_ertm=1
No karg changes needed
Generic device detected. Performing setup...
No fstab param adjustments needed
Current minimum-free ZRAM value: 130464
No minimum-free ZRAM changes needed
```
=> fix(gpd) don't rotate GPU Win Mini 2024 7640U display

Containerfile
Add `wqy-zenhei-fonts` package under `google-noto-cjk-fonts` to let GoldSrc engine display Chinese characters. 
Old GoldSrc engines (Half-Life, Counter-Strike 1.6, Condition Zero) and potentially some Source 1 games, are using `wqy-zenhei` to display Chinese characters. On default installation, the package is not included resulting in blank characters being displayed.
It's the well-known solution being mentioned multiple times on [Source-1 repo](https://github.com/ValveSoftware/Source-1-Games/issues?q=wqy-zenhei) and somewhere on the internet that I'm not able to find discussion threads anymore.
After layering the package `wqy-zenhei-fonts` the results are shown below.
It also fixes not just Chinese but also special symbols.
=> feat: Install `wqy-zenhei-fonts` for GoldSrc engine to display Chinese fonts

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
currently `ujust setup-decky` does nothing, whereas previously it defaulted to start installing decky
change the default action to be `install`
edit: just noticed the setup-decky usage doc was incorrect
=> fix(ujust): set install as the default action for the setup-decky ujust

.github/workflows/sign_image.yml
Creates a GitHub Actions workflow to sign an individual image with Cosign.
Accepts an input string, containing the image name and tag (for example `ghcr.io/ublue-os/bazzite:20240230-something`), and will push an updated signature.
This _should_ allow maintainers to re-sign older images with the new cosign keys, allowing users to rebase from new to old versions.
Please test this in an image from the testing branch before running it on something people depend on.  I don't see what could go wrong, but you never know.
=> chore(ci): add a workflow to manually sign an image with Cosign

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Disables MCU powersave for Ally X. Thank you Asus.
=> fix(Ally X): disable MCU powersave

Containerfile
Adds [fcitx5-hangul](https://github.com/fcitx/fcitx5-hangul) to enable Hangul (Korean) input in KDE.
=> feat(kde): add fcitx5-hangul for Korean input

Containerfile
This is not fixed upstream. Calling `wine32` to run a program doesn't run the wineserver automatically. If you run the wineserver manually it will look for `wine3264`.
=> Revert: chore: Fixed upstream

system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Kills steam, removes all files except userdata, games, controller profiles, music and compatibilitytools/custom-proton then starts steam again using `bazzite-steam`.
=> feat(just): add ujust to reset steam

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
For users on Steam Beta, Decky pre-release is usually required.
This adds a `ujust setup-decky prerelease` option for convenience.
=> feat(just): add decky prerelease option

system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/51-preferHDMI.conf, system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/60-raise-internal-mic.conf
Currently, there's an issue with the internal mic not being default in gamemode. Also, this gives priority to HDMI/external audio if Legion Go is attached to HDMI audio. Added 2 conf files to wireplumber.conf.d.
This is related to the post here: https://universal-blue.discourse.group/t/legion-go-microphone-does-not-default-to-correct-card-in-gamemode/3215/5
=> fix(LGO): fix audio input and output priorities for Legion Go

.github/workflows/build.yml
Adds image rechunking to the bazzite build. May or may not run as it is. Before being moved to testing, the action and docker image used should be pinned.
Especially since ref points to a local filesystem dir, which the upload action might not like.
=> feat(rechunk): Introduce image rechunking to lower update sizes

.github/workflows/build.yml
Bumps rechunk to ver 0.2.1 which makes it fail gracefully if it does not find a previous manifest and enables previous plan lookup on the unstable branch to test successive builds.
Eventually, all branches should look to stable for their previous plan, as that will provide a good baseline for users from stable rebasing to them. But for now only the unstable manifest contains a previous plan.
PR will be upgraded from draft after rechunk CI runs
=> feat(rechunk): enable previous layer checks and bump version

system_files/desktop/shared/usr/lib/systemd/system/bluetooth.service.d/prevent_hanging.conf
Better fix than pr #1390 addressing both, controllers unable to disconnect on suspension and devices not being able of entering suspension
=> fix: Prevent bluetooth preventing suspension

Containerfile, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
This adds a command to allow running a benchmark directly from ujust. Apprently this is a thing in other ublue variants, so I simply ported it over from bluefin.
=> feat: Add ujust command for stress-ng benchmark

system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/60-raise-internal-mic.conf
Priority didn't need to be so high. Add a description to see it in wpctl status.
=> fix(LGO): reduce input source priority and add description

system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/51-preferHDMI.conf, system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/alsa-card0.conf, system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/alsa-card1.conf
Create rule for HDMI and new folder structure for wireplumber for Ally X.
=> fix(Ally X): prefer HDMI audio when docked

Containerfile
Related to https://github.com/ublue-os/hwe/pull/273
We have been experiencing multiple freezes with the newly released Nvidia 560 drivers, so we will pin to 555 while we investigate.
I suggest this be unpinned in the testing stream before making this change in any end-user facing images.
=> fix(nvidia): pin Nvidia drivers to 555

system_files/desktop/shared/etc/profile.d/open.sh
This just makes `open blah.pdf` and so on work via the command line. It opens whatever app is set for that mime type
=> feat(cli): Alias `xdg-open` to `open`

system_files/nvidia/shared/usr/libexec/nvidia-legacy-hardware
Adds `/usr/libexec/nvidia-legacy-hardware` as a script on nvidia images.
will exit 1 if the machine has no legacy nvidia cards.
I did not add this to the non nvidia image as it is nvidia specific and we also do not want to risk the updater rebasing users from a non nvidia image to an nvidia image if they use the card for gpu passthrough.
once we have tested this here we can look into adding it to nvidia hwe or bluefin until migration period is over
PS: thankfully nvidia has way more sensible names than amd for their gpus as part of their PCI ID data
=> feat(nvidia): add script check for legacy nvidia hardware

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
`bazzite-rollback-helper list`
lists available bazzite images that can be rebased back to.
However, due to a recent change in tag names, this is no longer capturing the newest tags.
previous tag format:   `"40-stable-20240809"`
new tag format: `"stable-40.20240809.0"`
This PR updates the command to capture both the previous and new tag formats.
Example of new output
```bash
$ bazzite-rollback-helper list
Listing images for stable
"stable-40.20240815.0",
"stable-40.20240809.0",
"40-stable-20240809",
"40-stable-20240807",
"40-stable-20240804",
"40-stable-20240803",
"40-stable-20240802",
"40-stable-20240801",
```
=> fix: update bazzite-rollback-helper list to capture new image tags

.github/workflows/build.yml
Leftover from previous PR had rechunk using the KDE package mapping from unstable for all images. This caused an increased update size.
Once verified to work, use the fresh-rechunk button to fix current mappings.
=> fix(rechunk): use correct previous ref

spec_files/steamdeck-kde-presets/nested-desktop-resolution.patch, system_files/desktop/shared/usr/bin/waydroid-launcher, system_files/desktop/shared/usr/libexec/waydroid-container-start
This PR allows external scripts to specify the nested-desktop/waydroid screen dimensions by allowing overrides for the `_WIDTH` and `_HEIGHT` environment variables.
This allows for a user to provide their own launcher scripts which may detect the current display resolution using `xdpyinfo` or `wayland-info -i wl_output`. For example:
```bash
#!/bin/bash
set -euo pipefail
if [ -z "$DISPLAY" ]; then
echo 'No $DISPLAY attached to current session.' >&2
exit 1
fi
if [ -z "${GAMESCOPE_WAYLAND_DISPLAY:-}" ]; then
zenity --error --text="This script can only be run in a gamescope session."
exit 1
fi
_DISPLAY_RESOLUTION="$(xdpyinfo | awk '/dimensions/ {print $2}')"
export STEAMOS_NESTED_DESKTOP_WIDTH="${_DISPLAY_RESOLUTION%x*}"
export STEAMOS_NESTED_DESKTOP_HEIGHT="${_DISPLAY_RESOLUTION#*x}"
exec …
```
=> feat: allow external scripts to specify nested-desktop/waydroid dimensions

system_files/overrides/usr/share/fish/vendor_conf.d/brew.fish
**fish shell** take long time to be ready since **homebrew** vendor script must be executed in every shell instance.
I substitute the brew instance by a function that evaluates those commands which are slowing down the fish initial runtime only when you call brew _"when you need it"_
=> feat(fish): enhanced fish performance

.github/workflows/build.yml
Hi, thanks for fixing my syntax yesterday (as I have no way of checking locally). Oups.
Using stable as a reference was intentional. Since both unstable and testing are by their nature not stable and happen more often than main, having them diverge in their packaging increases the chance that a) rechunk will fail and will need cleanup sooner and b) when users switch between the 3 main branches they get a much larger download.
Therefore, always use stable when calculating the new plan.
As for the unique version tag, the IMAGEREF points to the same ghcr repo, so all of the tags get referenced always. This will not result in duplicate tags in testing/unstable.
=> chore(rechunk): Always use stable tag

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
add a ujust that posts gamescope logs via fpaste, along with dmi info + gpu
`ujust post-gamescope-logs`
example output file:
```
GPU info
*-display
description: VGA compatible controller
product: Rembrandt [Radeon 680M]
vendor: Advanced Micro Devices, Inc. [AMD/ATI]
physical id: 0
bus info: pci@0000:74:00.0
version: c1
width: 64 bits
clock: 33MHz
capabilities: vga_controller bus_master cap_list
configuration: driver=amdgpu latency=0
resources: iomemory:7f0-7ef iomemory:7f0-7ef irq:43 memory:7fe0000000-7fefffffff memory:7ff0000000-7ff01fffff ioport:f000(size=256) memory:dc700000-dc77ffff
File: /sys/devices/virtual/dmi/id/bios_date
10/27/2022
File: /sys/devices/virtual/dmi/id/board_name
G1619-04
File: /sys/devices/virtual/dmi/id/board_vendor
GPD
File: …
```
=> feat(ujust): add post-gamescope-logs ujust

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
upstream removed `libvirt` as a dependency for virt-manager 🙃
=> fix(just): add libvirt package to setup-virtualization

.github/ISSUE_TEMPLATE/bug-report.yml
We've had a user try to trick our users by posting links to download scam binaries as a solution to their reported issue. This still needs more work but doesn't hurt to ask. 
It's easy for us to delete the comments when reported but we're not on 24/7.
=> chore: add a warning to the issue report template

docs/src/Handheld_and_HTPC_edition/Change_Physical_Keyboard_Layout_for_Steam_Gaming_Mode.md, docs/src/SUMMARY.md
It's now part of the Steam Gaming Mode documentation.  Yes I know this also affects Gamescope on the desktop too, but that information should be documented upstream anyways.
=> chore(docs): Delete Physical Keyboard Layout

Containerfile, README.md
Konsole can be re-acquired by Flatpak if necessary for some reason.
https://flathub.org/apps/org.kde.konsole
=> feat: Remove Konsole & GNOME Terminal to save space in-image

.github/workflows/build_mkdocs/action.yml
This change will run mkdocs build with 3 attempts in order to handle a possible timeout by discourse.
=> ci(docs): Add retry logic to build_mkdocs

system_files/desktop/shared/usr/bin/cec-control
Recently acquired a Pulse Eight USB CEC device and found bazzite wasn't switching on boot or other events it looks like it was configured to do switching on.  Found a fix for the script that should enable it to work again and not only turn the TV on, but also switch inputs.
=> fix(cec-control): compare variable rather than variable name

.github/workflows/deploy_docs.yml, docs/hooks/cmdrun.py
Likely was caused by the lack of `re.UNICODE` flag when searching for discourse urls to be replaced
=> chore(docs): fix cmdrun breaking image url replacement

docs/theme_overrides/main.html
Keeping the warning for at least 2-3 more days.
=> chore(docs): Last change to warning

docs/src/Gaming/Game_Launchers.md
Probably a big mistake, but it's still somewhat hidden deep within one of the gaming guides (and the search).  Sick of seeing the question.
=> chore(docs): Add a shortcut for auto-mounting drives

README.md
fix(documentation): fix screen overclocking variable and values
The old variable did not work anymore, and the Steam Deck LCD screen glitches out past 69Hz.
I have however chosen 68Hz as the cap because this is used for 17/34/68FPS whereas 69 is only used for 23/69FPS. I also assume there's gonna be some displays that can't reach 69FPS.
=> fix(documentation): fix screen overclocking variable and values

system_files/deck/kinoite/usr/libexec/hardware/needs-left-rotation, system_files/desktop/shared/usr/libexec/bazzite-hardware-setup, system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
However this sysid is shared between the 16gb model and the 32gb model ~~will this cause issues with the GTTSize being applied if this happens on a 16GB model? or will i have to separate out the 2 models in hardware setup by adding additional checks.~~
=> feat: add support for onexfly 8840U

docs/README.md
@Zeglius I initially edited the README for the docs because of the "cant" for grammatical purposes, but I also removed a bunch since we're past the transcribing part.  Anything I should bring back or add?
=> chore(docs): Documentation Documentation Fix?

docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
PauseGames plugin works on Bazzite, this PR updates the docs with a more up-to-date example
=> chore(docs): Update outdated info in docs related to Decky

docs/theme_overrides/main.html
I am in the process of editing the rest of the documentation to have it on par with the final changes I made to the Discourse version before the Github transcription happens.  That PR will happen either later today or tomorrow, but by the end of the week the Discourse documentation will no longer be updated ever again and will remain the old, unlisted documentation.
The docs (or user guides as I view them) now live here and can be modified in any way that both consistent maintainers/contributors and new users who want to edit the documentation (and gets approved) sees fit.
=> chore(docs): New announcement for documentation

docs/src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md
ref: https://github.com/ublue-os/bazzite/issues/1405#issuecomment-2277027806
I have also just done a Bazzite install on my Steam Deck Oled 1TB which arrived this morning (with regular graphics mode) 😝
=> docs: steam deck oled no longer requires basic graphics mode

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
On certain devices, such as the ROG Ally X and ROG Ally, as well as some AMD laptops, performance becomes more unstable/worse when the device is taken off AC power.
This workaround adds a udev rule that runs `ryzenadj --max-performance` when a device is taken off AC power, which basically tells the APU to continue behaving as if it's on AC power.
original source of fix: https://github.com/aarron-lee/legion-go-tricks/blob/main/ryzenadj-max-performance.sh
=> feat(ujust): add ujust for ryzenadj --max-performance

system_files/desktop/shared/usr/bin/btrfs-dedup
=> fix: btrfs-dedup don't wait on compsize since compsize doesn't run

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
The `just` recipe for `install-deckhd-bios` fails because it can't correctly infer the resolution (#1679). By using `xrandr`, we can correctly infer the resolution and install the correct bios.
=> fix(deck): update just recipe to infer DeckHD bios install

Containerfile
Removes the framework akmod installation since this is being removed from the ublue-os/akmods repo in [this PR](https://github.com/ublue-os/akmods/pull/239).
All changes required for Frameworks should have been moved upstream, so this is redundant.
Bluefin has already removed this akmod a while back.
=> chore: remove framework akmod install

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Add a warning text for invalid options provided to bazzite-rollback-helper
=> chore: add warning text for invalid args to bazzite-rollback-helper

system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Bazzite is currently missing way too many devices. We support the whole catalog for all three manufacturers so add all of their devices to the auto-detection.
=> chore(hhd): add OneXPlayer, Ayaneo,  and GPD to hhd supported devices

.github/workflows/build.yml, system_files/desktop/shared/usr/libexec/containerbuild/image-info
Modifies build-id to contain a pretty version of the version information. Then, changes that pretty version (in testing) to contain the git hash of the commit that built the image.
To make the image repo sync with what the device reports, the suffix is removed from the upstream build ID and a shortened SHA suffix is added to the tag for testing and unstable.
After these changes, there is no practical difference between testing and unstable, so their options are synced.
=> chore: Cleanup version information to be more intuitive

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
bazzite setup seems to run with root priviledges as it writes to /etc directly. However some commands use sudo.
For some reason, using sudo delays boot by over 2 minutes in certain instances. So remove it.
Also remove pmf script from Ally since it is part of 6.11.
=> chore: remove sudo from bazzite setup script

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
this adds a ujust toggle for enabling/disabling password feedback in terminal
=> feat(ujust): add pwfeedback toggle

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
Updates the gamescope patches to allow the following:
- lua configs with only refresh rates to work (previously would also need generation logic)
- fixes Ally refresh rate limiter to work across the whole refresh range
- VRR down to 48hz
- Below, automatically disable VRR
- Makes SteamUI run at half refresh when refresh rate is above 60hz (e.g., 60hz on the Ally, 72hz on the legion go)
- Disables VRR while on SteamUI (should help with LFC flashing after SteamUI stops blanking)
In addition, since chimeraos gamescope patches account for less than 50% of the patches, it renames it appropriately.
=> feat: update gamescope patches with new features

spec_files/pipewire/pipewire.spec
This tracks upstream changes:
https://src.fedoraproject.org/rpms/pipewire/c/2172a5be56c50d8add5074b9d5422b49e0cd2b50?branch=f41
The changes are:
- version
- man page filename
- changelog
(And some whitespace only changes from me using the upstream copy of spec)
Relates: #1774 
Since I put in the PR for the F40 update, why not also the F41!
=> chore: update f41 pipewire to version 1.2.6

spec_files/gamescope/handheld.patch
The previous patchset had a bug where automatically disabling VRR on steamui did not apply correctly and could affect VRR in games. This change makes it so VRR is disabled globally while in steamui, which should also help with frame pacing. It also fortifies the logic of whether VRR should be enabled, which should catch edge cases.
Also moves honjow's patch lower to make rebasing easier.
=> fix: fix VRR disable in SteamUI to work correctly

.github/workflows/build.yml
currently, ostree-rs-ext in rechunk uses compression, which makes it take 40% longer. In addition, we tag images with both the upstream tag and the unique tag (e.g., `20240420.0` and `20240420.3` or `20240420`) which is confusing, so those should be removed.
=> chore: Remove rechunk compression and spurious tags

.github/workflows/changelog.py
We cut the suffix from the wrong place, which makes the title and first sentence of the changelogs incorrect.
=> fix: fix version number in changelogs

.github/workflows/changelog.py, .github/workflows/generate_release.yml
Currently, the target is used to determine whether a release should be marked as prerelease. If it starts with `refs/head/` the check will break. So truncate to after the last `/`.
Then, add a rebase command for existing users that want to use the image.
=> chore(changelog): Tweak changelog with rebase command, ignore refs in target

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
add optional arg for to explicitly turn pwfeedback on/off
```
ujust toggle-password-feedback on
ujust toggle-password-feedback off
```
useful for programmatically turning on/off pwfeedback
e.g. in the Bazzite portal
=> feat(ujust): Update pwfeedback ujust to include optional arg

system_files/desktop/shared/usr/bin/bazzite-rollback-helper, system_files/desktop/shared/usr/bin/brh
This PR:
* isolates each helper subcommand in the helper (list, rebase, current and rollback) into their own function for easier maintenance.
* Adds a "brh" symlink pointing to bazzite-rollback-helper (too long of a name for a script)
* Fixes some inconsistencies with "current" subcommand output
=> chore: Rewrite of bazzite-rollback-helper and shorter name

.github/workflows/changelog.py, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
I accidentally added the pwfeedback ujust to the `-deck` images only, when it should've been made available for all images.
Mistake on my part, this PR moves the ujust to the correct file. thanks for flagging this @nicknamenamenick
=> fix(ujust): move pwfeedback ujust to correct file

.github/workflows/generate_release.yml
Whoopsies you put it in the python script so last release is tagged as prerelease.
=> fix(changelogs): change main to stable

spec_files/gamescope/handheld.patch
Previous patch halved the blanking interval of SteamUI without updating the presentation timings. This might have caused it to feel choppier than it should. Therefore, much like VRR, add a staging variable for the requested framerate and only apply it when we are not in SteamUI.
This way, the wayland presentation callbacks and timers have the correct frame pacing.
Then, add `--disable-steamui-framelimit` to disable the optimization. Even with that flag, VRR will remain disabled in steamui.
=> fix(gamescope): improve SteamUI refresh halving

Containerfile
We removed in commit 28e5a48 due to upstream issue. This has been resolved. We need to merge https://github.com/ublue-os/akmods/pull/258 and build akmods before merging this into main.
Closes: https://github.com/ublue-os/bazzite/issues/1801
=> feat: add_evdi back for F41

.github/workflows/build.yml
Podman uses an inferior gzip compression to ostree-rs-ext, which adds 500mb to the image. In addition, pulling the image to podman requires 3 min. So reorder the steps to save some time and image space.
Looking at the action again it takes only 2.5 min and uploading with podman is slightly faster so it might not be worth it.
=> chore: Reorder the build steps to save time and image size

spec_files/gamescope/handheld.patch, system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Adds atom for controlling whether we halve the hz in SteamUI. See https://github.com/hhd-dev/hhd/commit/ea00e99a446f0face75f82b95bd6d801ac7f7efc
=> feat: Add atom for controlling refresh rate halving in Steam

.github/workflows/build.yml, .github/workflows/promote.yml
The autoupdater pushed a partial update today, and the previous update broke the framework kmod (because it is now "upstream")
The update regression rate is too high for the current state of bazzite, for the vast majority of its users.
That being said, there are a lot of users that like to be a bit ahead.
Therefore, gate the stable builds behind an `edge` tag for power users, and add a small action to promote the current `edge` build to `stable` once it has been validated to work.
Just in time for F41. 
The regression in this update was small: the Ally frame limiter stopped working and we were caught by surprise. It would have been worse, as with F41. The edge channel also allows us to update that channel to F41 earlier than Fedora.
=> chore: gate stable and add promotion action

system_files/desktop/shared/usr/share/ublue-os/just/83-bazzite-audio.just
Updates the `ujust` to setup virtual surround to use the new PipeWire Spatializer module in place of the older HeSuVi-style convolver.
Not only is this method now recommended in the PipeWire Wiki, but free `.sofa` HRTF files are much more plentiful online; which is particularly relevant given head-related transfer functions must pertain to the individual's anatomy for proper effect. 
The sample HRTF is downloaded from the Sofacoustics database in the script, with the original measurements from MIT being freely available [here](https://sound.media.mit.edu/resources/KEMAR.html), where they're allowed free redistribution.
Additionally, I've taken the liberty to add small step-by-step instructions at the end of the script's execution, including links, as to how to identify and obtain a …
=> feat(just): Update surround to use spatializer

Containerfile, system_files/desktop/shared/usr/bin/boot-windows, system_files/desktop/shared/usr/share/ublue-os/just/86-bazzite-windows.just
I'm seeing a number of people using my https://youtu.be/WR31wkrxock video for making a script to boot into Windows from Steam in GameMode. However, quite a few people miss a step or type a character incorrectly. Thought that it might be possible to automate this with a ujust script.
Also want to give thanks to u/0nlin3 on Reddit for the idea.
=> feat(ujust): Add setup-boot-windows-steam ujust script

system_files/desktop/shared/usr/bin/bazzite-steam
the check used the old path to the valve-hardware script
=> fix(bazzite-steam): correctly add the HHD steam controller on non valve hardware

system_files/desktop/shared/usr/bin/protontricks-launch
This is a partner script to `/usr/bin/protontricks` to be able to run .exes via commandline.
=> Add protontricks-launch to run .exes via commandline

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Puts the toggle-password-feedback ujust on all images and not just the deck images.
=> fix(just): add toggle-password-feedback to all images

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
@antheas pointed out I had typoed the original ujust so i have to just live with it.
This improves the `install-speaker-firmare` to be correctly spelled `install-speaker-firmware` and also makes the ujust recipe more dynamic so it does not have to be updated when new speaker firmware is added.
Since this script will be loaded externally it will also be displayed to the user for visual verification before running (unless the `yes` or `-y` action is passed)
if this is to be added to yafti then it has to be called with `sudo -A ujust install-speaker-firmware yes`
in the terminal `ujust install-speaker-firmware yes` will be preferred as it will ask for sudo when needed (and avoiding "teaching" users that some ujusts should be run with sudo... which then causes them to use it on all of …
=> feat(just): Improve install speaker firmware

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
Adds DPMS support to gamescope through an atom to fire it prior to suspend in the future (NOOP by default), turns off the 60hz optimization by default and removes the arg for it as HTPCs do not need it and HHD will turn it on automatically now, and pins to latest master as of this writing.
=> feat: add DPMS support to gamescope + disable 60hz by default

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
DPMS would not fire correctly if the screen did not blank, causing it to happen after suspend around 20% of the time. Force it to fire even if there is no new frame.
After suspend, steam refreshes the display anyway so it is not an issue.
HHD controls the blanking so this is a prerequisite to adding that functionality.
=> fix(gamescope): force dpms even if steamui is not blanking

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Adds back an accidentally removed line in `ujust install-lact` that sets an amdgpu karg
=> fix: reinstate ujust install-lact karg modification

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
...Hopefully.  I am a little busy and have to drive for a bit, but if this works, can someone please apply these changes to Desktop images if I don't get around to it today or something?
=> fix(yafti): Fix Bazzite Portal not launching on -deck images

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
GPD Win Mini experiences a display crash after sleep when using the DPMS function. Gamescope stops showing stuff on the screen but you can still hear steam in the background. Remove the early present which might be causing this.
https://github.com/hhd-dev/hhd/issues/115
=> fix(gamescope): remove dpms early path which may be causing a crash

.github/workflows/build.yml, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
This is a fix for #1930 the "Install More Applications" at the end of the Bazzite portal wizard will now open Gnome Software  when running bazzite-gnome or bazzite-deck-gnome rather than doing nothing.
=> fix(yafti): Install More Applications button not opening gnome-software in bazzite-gnome

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
While looking through the system journal, I noticed one of the Bazzite scripts was throwing an error on boot:
```
Dec 04 18:46:39 bazzie bazzite-hardware-setup[1936]: /usr/libexec/bazzite-hardware-setup: line 268: -f: command not found
```
This is coming from a recent change (https://github.com/ublue-os/bazzite/commit/389f4a55c905b1efef50dd0bce9ad373543add3d) that is trying to update the `/etc/tuned/ppd.conf` file if it exists, but the existence check is missing brackets.
=> fix(tuned-ppd): correct config existence check in bazzite-hardware-setup

spec_files/mesa/indiana.patch, spec_files/mesa/mesa.spec
Imports the following two commits into Mesa 24.2.7:
https://gitlab.freedesktop.org/hakzsam/mesa/-/commit/b302d9fec18b7c3c045ae53f980824e8734b92f3
https://gitlab.freedesktop.org/mesa/mesa/-/commit/3f31161eb36680a2b78d935e9018e32280cc8fe3
Game is still not perfect but it's a marked improvement over extreme corruption.
=> fix(mesa): add temporary patch for Indiana Jones and the Great Circle

system_files/desktop/shared/usr/share/ublue-os/motd/themes/pink.json, system_files/desktop/shared/usr/share/ublue-os/motd/themes/purple.json, system_files/desktop/shared/usr/share/ublue-os/motd/themes/red.json
Fix for https://github.com/ublue-os/bazzite/issues/1972.
Invalid JSON was causing an error whenever shell was booted.
=> fix: fix trailing commas in JSON

.github/workflows/build_iso.yml
Change the static repo links in the build_iso workflow to dynamic ones.
Part of changes needed to allow for custom images using GitHub Actions
=> fix: remove static links from build_iso workflow

.github/workflows/build.yml
Splits the image registry variable into different pull and push variables.
Part of changes needed to allow for custom images using GitHub Actions
See also: #1977
=> fix: split image registry variable in build workflow

spec_files/mesa/indiana-2.patch, spec_files/mesa/mesa.spec
since the indiana patch got pwned in the mesa bump (why didn't they add them), re-backport the patches. should be up to speed with upstream mesa
=> fix(mesa): re-backport indiana jones patches for 24.2.8

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-sunshine.just
If we decide to switch to sunshine being included in the Bazzite image, its service would be off by default like sshd. So I've adjusted the logic in the yafti.yml files to only enable the service. I've adjusted the `ujust setup-sunshine` script too accordingly.
I'm not certain if the sunshine-workaround.service is needed or not but I've included it in the enable and disable logic
=> fix: Adjust yafti and sunshine ujust for layered version of sunshine

system_files/desktop/shared/usr/share/ublue-os/just/86-bazzite-windows.just
This is a fix for #2017, looks like the `/usr/bin/steamos-add-to-steam` file isn't available on Bazzite Gnome desktop, so I've removed the reliance on this script file in the `ujust setup-boot-windows-steam` script
=> fix(ujust): removed removed script dependencies for ujust setup-boot-windows-steam

system_files/overrides/usr/share/bazzite-cli/bling.sh
Port of https://github.com/ublue-os/bluefin/commit/76d7d71e900902845f3e715da85affe4dce52b7a from the bluefin repo. Should fix atuin getting sourced multiple times
=> fix: return on bling.sh if it already got sourced

.github/workflows/build.yml
ArtifactHub requires the raw README file, not a website.  
Currently this is not being rendered correctly, and is only showing HTML of the website (which is not useful).
=> fix: update ArtifactHub README.md

Containerfile, system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Adds the latest [ls-iommu](https://github.com/HikariKnight/ls-iommu) tool to the image and updates the virtualization ujust to no longer rely on initramfs regeneration as bootc does not support that.
=> feat: add ls-iommu and update virtualization ujust for bootc transition

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
New year new busted release. Revert to previous stable hash that is known to work.
=> fix(gamescope): revert to previous tag as latest release is busted

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Only hide grub on successful boot, set GRUB_HIDDEN_TIMEOUT (which is not set by default) to 2 if its not set so that GRUB_TIMEOUT=5 is not used when hiding. Users that hid grub are unaffected.
=> fix(grub): autohide on successful boot

system_files/desktop/shared/usr/bin/bazzite-steam
Steam beta client has some new video locations. Unlike the previous, they now have different videos for oled, deck and generics.
=> fix(steamui): add new video override locations

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Surprise @KyleGospo i couldn't stop myself
=> feat: add libvirt qemu hook to setup-virtualization

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
maybe writing the previous PR at 3am was a bad idea?
=> fix(just): display libvirtd hooks guide after it is downloaded

system_files/desktop/shared/usr/lib/dracut/dracut.conf.d/80-vfio.conf
should fix issues where the nvidia module and amdgpu module manages to snag the gpu first on some machines.
=> fix: force vfio modules to hopefully load before gpu modules

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
As of changes noted in: https://universal-blue.discourse.group/t/bazzite-3-7-0-update-released/3726, version numbers for Bazzite have been deprecated along with their associated changelogs. Releases are now signified by `yyyymmdd` format with auto-generated GitHub release notes.
The `ujust changelog` and alias `ujust changelogs` commands currently reference the outdated `CHANGELOG-SHORT.md` file, which has not been maintained since Bazzite 3.7.0.
This PR updates the `ujust changelogs` functionality to fetch the latest auto-generated release notes directly from GitHub, ensuring users can quickly access relevant changes.
- Adjusted `ujust changelogs` to fetch the latest stable release notes via the GitHub API.
=> fix(deck): update 'ujust changelogs' to pull latest release notes from GitHub

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
This PR introduces the following updates and fixes:
1. **`restore-gamemode-shortcut` Command**:
- Adds a new `ujust` command to restore the "Return to Gaming Mode" shortcut on the Desktop.
- The shortcut is copied from `/etc/skel/Desktop/Return.desktop`, ensuring it matches the original system-provided file.
- Includes checks to prevent overwriting the existing shortcut or failing silently if the source file is missing.
- Sets executable permissions for the shortcut to ensure functionality.
- Provides meaningful feedback to users at every step.
2. **Restored `configure-grub` Command**:
- Reintroduces the `ujust configure-grub` command with enhanced functionality using `ugum` for a more user-friendly, styled CLI interface.
- Users can now:
- View the current GRUB `menu_auto_hide` setting …
=> feat: Add 'restore-gamemode-shortcut' and restore 'configure-grub' with ugum styling

Containerfile
steam.desktop has a Desktop Action entry to in BPM, and would pop up in the app search.
This modifies the action to use `bazzite-steam-bpm` instead.
=> feat: replace steam BPM buitin action

system_files/desktop/shared/usr/bin/bazzite-steam
This disables the video replacement step if the Animation Changer plugin is found. Given that they are probably trying to change the animation themselves, we should probably get out of their way.
=> feat(deck): Disable animation replacement for plugins.

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
change just recipe for opentabletdriver to use flathub version
=> feat: change opentabletdriver installation to flathub version

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Too large of a download to setup a container for a first-time setup utility which confuses new users when the device goes to sleep and it breaks among other issues.  It will still be available as a `ujust` command.
=> chore(yafti): Remove scrcpy from the Bazzite Portal

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
First, do some reverts to fix our shame with trying to get master. Master has some openvr stuff we dont care about so we can procrastinate on it.
Then, cherry Matt's hotkey fix, add legion config that only works properly with our vrr patch, and fix external rotation when applying the rotation shader on intel
=> feat(gamescope): add legion, cherry hotkey patch, fix externals on Intel rotation

system_files/desktop/shared/usr/libexec/waydroid-container-restart, system_files/desktop/shared/usr/share/applications/waydroid-container-restart.desktop, system_files/desktop/shared/usr/share/polkit-1/actions/org.bazzite.waydroid.policy, system_files/desktop/shared/usr/share/polkit-1/rules.d/30-waydroid.rules, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
Occasionally the Waydroid container becomes unresponsive, but a simple force restart fixes it. This just adds a convenience shortcut for it.
=> feat(waydroid) - Add waydroid force restart shortcut

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
change openrazer just recipe to only install the daemon and use polychromatic/razer genie from flathub
=> feat: change openrazer just recipe

system_files/desktop/shared/usr/lib/systemd/system/bazzite-libvirtd-setup.service, system_files/desktop/shared/usr/lib/tmpfiles.d/bazzite-libvirt.conf, system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Improve the bazzite-libvirtd-setup.service to restore SELinux context and prevent running the setup-virtualization script as root.
Fixes issue #2115.
=> fix(virt): Enhance service setup and restrict root execution for virtualization script

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Fixes the command `changelogs-testing`, introduced in #2137 .
=> fix: typo in readable changelogs

system_files/deck/shared/usr/bin/bazzite-desktop-bootstrap
It is now set once and not touched unless `~/.config/bazzite/fixups/scaling_fixup` is removed.
=> fix(deck): don't force scaling each time desktop loads

system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Lenovo blessed us with more variants. Also, remove devices that are caught by the manufacturer check above. Exception is ONE XPLAYER, because it is prior to OneXPlayer's rename.
=> chore: add more Legion Go S variants and dedup

Containerfile
Because filename changes from origin
=> fix: Whole github 404 page was fetched into `/etc/distrobox/incus.ini`

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
The post-gamescope-logs command was designed to collect Gamescope-specific logs from legacy file paths. These files are no longer generated because Gamescope now sends all log output to the system journal (journald).
this PR replaces that ujust recipe with a new one 'get-logs' that cleanly outputs two pastebin URLs for logs this boot, and logs last boot. This optimizes for issue reporting and troubleshooting. You can just tell the user "run 'ujust get-logs'" to get output like:
```
Logs This Boot: https://paste.centos.org/view/84d14e25
Logs Last Boot: https://paste.centos.org/view/0e8f36e3
```
this command is intentionally short and the output hides warning messages and other noise, in order to optimize for users who may be inputting this with touch keyboards on small handheld screens.
=> feat: easier troubleshooting with 'ujust get-logs', depreciate gamescope-logs

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
fix(X1 Pro): fix screen rotation on OneXPlayer X1Pro
=> fix(X1 Pro): fix screen rotation on OneXPlayer X1Pro 

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
This ensure us that we replace preinstalled fedora flatpaks instead of suffering collision.
=> fix (justfile): Add '--reinstall' flag

.github/workflows/build.yml
github-cli requires be given a token in order work inside github actions
=> fix (docs): Missing GH_TOKEN for pulling offline docs

Containerfile, system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
- add launch option: '~/fgmod/fgmod %COMMAND%' to run fgmod script at game launch and enable FSR3 upscale and Framegen via in-game DLSS options
- add launch option: '~/fgmod/fgmod-uninstaller.sh %COMMAND%' to run uninstaller script at game launch to revert mod application, replace original game files, and pass through to execute game
- alternatively, use Decky Framegen to patch or unpatch steam games with a single click
Scripting sourced from https://github.com/xXJSONDeruloXx/fgmod-bazzite which is forked from https://github.com/FakeMichau/fgmod
=> feat: add ujust get-framegen

Containerfile
Hiya! I'd like to suggest adding `kcm-fcitx5` for better integration with KDE:
1. Users can tweak their Fcitx5 settings in `System Settings / Input Method` instead of launching Fcitx5 individually.
2. Users can use `KDE Plasma (Experimental)` theme for Fcitx5, which is nice because it can dynamically generate theme to fit their Plasma theme. https://planet.kde.org/weng-xuetian-2022-07-04-fcitx-5-plasma-theme-support/
Thank you!
=> feat(fcitx5): add `kcm-fcitx5` for better integration with KDE

system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
bugfix ujust for suspend video overrides, currently it doesn't actually do anything
culprit is the `"$OPTION" =~ ^enable` and `"$OPTION" =~ ^disable` not having the correct capitalization
=> bugfix(ujust): fix suspend video override ujust

system_files/desktop/shared/usr/bin/bazzite-steam
It appears that the check was accidentally removed in this commit: https://github.com/ublue-os/bazzite/commit/0ac4502ce1cd05f59d7df53771c48239863dc9b3
This is just re-adding it again.
=> fix(deck): re-add the plugin check for video replacement

system_files/deck/silverblue/usr/share/ublue-os/just/90-bazzite-de.just
seems just syntax caused issues with recipe, also took the opportunity to improve error handling
=> fix: restore-gnome-de-settings - indent syntax, handle empty dirs, add error checks

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
simple fix, with sudo -A this adds plugin to root/homebrew/plugins, not user home directory. ujust in terminal works just fine, just the bazzite portal that has a minor issue
=> fix: rm sudo -A causing plugin install to root

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
udev rules is gone from image so this pr will add udev rules for opentabletdriver
=> feat: add udev rules to just recipe opentabletdriver

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
When using virt-manager as a flatpak is is impossible to use spice-client-glib-usb-acl-helper due to Flatpak sandboxing.
Without this tool USB redirection in running VM fails due to insufficient permissions.
To solve this issue I've added new options to virtualization ujust script which enable/disable udev rule allowing USB redirection (adding `uaccess` tag to all USB devices).
Rule uses `72` prefix to comply with https://github.com/systemd/systemd/issues/4288#issuecomment-348166161
=> feat: add USB hot plugging configuration for virtualization script

system_files/deck/shared/fwupd/fwupd.conf
Let's give the updater some time to mature. Users can update from Windows/manually for now.
=> fix: block LVFS on the Legion Go S for now

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
for some reason it was "autocorrected" to `/etc/libvirt/hooks/qemu/qemu.d` when it is supposed to be `/etc/libvirt/hooks/qemu.d`
=> fix(just): add correct path for libvirt hooks

spec_files/ds-inhibit/10-modprobe-ds.conf, spec_files/ds-inhibit/ds-inhibit.spec, system_files/deck/shared/etc/modules-load.d/hid-steaminput-preload.conf
this matches SteamOS and will work around racy behavior with Nintendo Switch controllers
=>  fix(deck): move hid preload from ds-inhibit to sysfiles and add hid-nintendo

system_files/desktop/shared/usr/lib/systemd/user/bazzite-user-setup.service
Porting https://github.com/ublue-os/aurora/pull/206, which I believe affects Bazzite as well. I think this is the only `systemd --user` service but I'm not entirely sure.
=> fix: only run bazzite-user-setup for human users

system_files/overrides/usr/share/fish/vendor_conf.d/brew.fish
Modified `/usr/share/fish/vendor_conf.d/brew.fish` line 7 from `.../brew` to `.../brew.fish`. This prevents `brew completions link` from running unnecessarily and significantly affecting fish startup times.
Resolves https://github.com/ublue-os/bazzite/issues/2228
See https://github.com/ublue-os/bazzite/issues/2228#issuecomment-2646194992 for more info.
=> fix: Fix incorrect completions path

system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
noticed there were some minor issues in this ujust as my new motherboard had one of the network cards where the WOL bit gets reset randomly at boot, meaning i needed to force enable this with a service file which then did not match the if condition in the script.
=> fix: Correctly detect if WOL is enabled and correctly create force-wol service file when create-service is choosen

README.md
It was removed from yafti with commit 191d32e3c1987c0e35596eaf69031407cfa0ce00
Fixes #2309
=> docs: Remove Gradience from README.md

Containerfile
This fixes /dev/dm-X devices not being excluded
=> chore: Bump media-automount-generator 0.2.3 -> 0.2.6

system_files/desktop/shared/usr/bin/scopebuddy
would essentially show mangohud twice
=> chore(scopebuddy): remove invalid example option

.github/workflows/build.yml
This will allow the reuse of build args for multiple image builds within the same job in a future.
=> ci: Store buildah build args in a file

.github/workflows/build.yml
This fixes nested quoted in the os-release
=> fix: Remove leftover quotation in build-args file

build_files/install-kernel-akmods
Change the installation source for the nct6687 RPM to the akmods-extra repository to ensure proper fetching of the package.
This fixes #2318
=> fix: Fetch nct6687 RPM from akmods-extra repository

system_files/desktop/shared/usr/bin/scopebuddy
No longer neccessary since the HDR fix
=> chore(scopebuddy): remove unused gsout var

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
`--no-lock` was recently removed from brew-bundle and is no longer valid.
See [Homebrew/homebrew-bundle@98d8ad7#diff-2ba13d1d1d9b7abcde49568b7aec20c97f4541f44f6befd62ac6a4d820ddb7ccL96-L98](https://github.com/Homebrew/homebrew-bundle/commit/98d8ad7ddcca7e7b700cd496207d51fa042c0b00#diff-2ba13d1d1d9b7abcde49568b7aec20c97f4541f44f6befd62ac6a4d820ddb7ccL96-L98)
=> fix: remove --no-lock from ujust bazzite-cli brew command

system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
This resolves issues with applications such as StreamController that uses the data/icons folder as part of its data structure.
#2332
=> fix(flatpak): remove flatpak data/icons override

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
=> fix: correctly quote KVMFR_MODPROBE heredoc and remove virtqemud_t from type enforcement

spec_files/gamescope/gamescope.spec, spec_files/gamescope/handheld.patch
Seems like gamescope does some cursed stuff on the internal panel of the F1 Pro and probably the Zotac Zone as well. Disable HDR autodetection for PQ EOTFs on internal panels for now and allow disabling on externals.
=> fix(hdr): Disable PQ HDR on internal panels and add option to disable on externals

Containerfile
Behavior is slightly different, now it will only mount labeled partitions. Mountpoint name no longer will be named after partition UUID, instead by the partition label.
=> feat: Replace old media-automount-generator package working one

Containerfile
Builds are failing right now because the latest dnf5 package version 5.2.11.0 has a regression that the Terra repos are exposing.
Related:
- https://github.com/ublue-os/aurora/pull/274
- https://github.com/rpm-software-management/dnf5/issues/2134
- https://github.com/ublue-os/aurora/issues/275
=> fix: downgrade dnf5 to avoid regression exposed by Terra

.github/CODEOWNERS
> If you want to match two or more code owners with the same pattern, all the code owners must be on the same line. If the code owners are not on the same line, the pattern matches only the last mentioned code owner.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Since it had never worked properly up to now, perhaps you should remove it
=> fix: make CODEOWNERS work

Containerfile
This package was renamed to add the switcheroo component to its name. This resulted in the old version 6.11 being picked up and downgrading from 6.12.
See latest Bazzite build logs:
```
2025-03-17T05:02:51.7115710Z Package "kf6-kio-core-6.12.0-1.fc41.x86_64" is already installed.
2025-03-17T05:02:51.7116496Z Problem: cannot install the best candidate for the job
2025-03-17T05:02:51.7117060Z   - conflicting requests
2025-03-17T05:02:51.7117326Z 
2025-03-17T05:02:51.7120311Z Total size of inbound packages is 4 MiB. Need to download 4 MiB.
2025-03-17T05:02:51.7121309Z Package                           Arch   Version                  Repository        Size
2025-03-17T05:02:51.7122138Z After this operation, 38 KiB will be freed (install 18 MiB, remove 18 MiB).
2025-03-17T05:02:51.7122819Z …
```
=> fix: kf6-kio package version mismatch due to renaming in Terra

Containerfile
the arguments gets essentially prepended now
see: 832cf110f6edc6da3b2c720c76e89656a47455bd
the final line looks like this then:
`Exec=plasma-discover --backends flatpak-backend --mode update`
=> fix: discover desktop entry exclusive flatpak backend enablement

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
CoolerControl is packaged in Terra, which is now included by default in all images; as that was already taking priority in release revisions anyway due to a higher number, it's probably better to remove this.
=> chore(just): Remove CoolerControl Copr import

Containerfile
ckb-next is an open-source driver for Corsair keyboards and mice.
Without including this in the base image usage of an rpm-ostree overlay would be required, as installing it via rootful systemd-enabled distrobox is not very straightforward or practical.
=> feat: Add ckb-next

system_files/desktop/shared/usr/bin/bazzite-steam, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
=> fix: enable get-decky-bazzite-buddy ujust to fetch latest, handle conflicting plugin names, clean old installs

system_files/desktop/shared/usr/bin/bazzite-steam, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
im fixing it out of sheer anger at Square Enix. Should let you still use -deck image and have game mode but not be forced to download the low quality asset version of rebirth, I believe theres a few other games like this as well, where SteamDeck=0 launch option wont suffice, as its the game files downloaded and depot chosen itself that is the issue
Discussion on the issue here:
https://github.com/ValveSoftware/Proton/issues/8408#issuecomment-2754226829
Here you can see Steam DB Depots for Deck which enforce lower quality assets on the install, which can not be overcome with launch args as the content is prevented from being installed in the first place:
https://steamdb.info/app/2909400/depots/
=> feat: add ujust toggle-steamdeck-alias to prevent games from force downloading low quality assets

system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Sudo calls are getting chained and thus SUDO_USER gets set as `root`
[The explanation](https://discord.com/channels/1072614816579063828/1087140957096517672/1358230705351426098)
=> feat: Prevent setup-decky with sudo

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
I discovered if using ujust toggle-steamdeck-alias on Bazzite to disable the -steamdeck launch flag, this works in desktop mode, but not in game mode (Gamescope session), where Steam still launches with -steamdeck.
In game mode, the CLIENTCMD variable is set in:
```/usr/share/gamescope-session-plus/sessions.d/steam```
as 
```export CLIENTCMD="steam -gamepadui -steamos3 -steampal -steamdeck"```
This setting ignores the flag file that desktop mode checks, so Steam is always launched with -steamdeck in game mode.
This update enhances the toggle-steamdeck-alias ujust recipe to fully support Bazzite’s immutable filesystem by using a writable override in ~/.config/gamescope-session-plus/sessions.d/steam.
Changes:
•	Automatically creates the sessions.d override directory if it doesn’t exist.
• …
=> Fix: Set -steamdeck alias in gamemode as well as desktop via ujust toggle-steamdeck-alias

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Fixes already existing installations like at #2466
=> fix: Always chown homebrew directory when running setup-decky

system_files/desktop/shared/etc/profile.d/bazzite-neofetch.sh, system_files/overrides/usr/share/fish/vendor_conf.d/bazzite-neofetch.fish
As requested by @adeliasvg:
This is to avoid issues entering `hyfetch` after installing the Homebrew package since the alias would return an error.
=> chore: Remove hyfetch aliases since there's a Brew package for this now

Containerfile
These packages exist upstream. I have removed the coprs for them.
=> fix: remove coprs for obs-vkcapture and vk_hdr_layer

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just, system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
This PR adds parameter support to various ujust commands to facilitate programmatic toggling and configuration in the upcoming OOBE (Out-of-Box Experience) replacement. These modifications allow scripts to be called with direct parameters rather than requiring interactive prompts.
- **Added parameter support to key system configuration scripts:**
- `toggle-ssh ACTION=""`: Enable/disable SSH with `enable`/`disable` parameters
- `configure-grub ACTION=""`: Configure GRUB visibility with `show`/`hide`/`unhide` parameters
- `toggle-wol ACTION=""`: Manage Wake-on-LAN with `enable`/`disable`/`force-enable` parameters
- **Added Jellyfin Media Player to streaming services:**
- Implemented Jellyfin installation option in `get-webapp` service menu
- Added proper Flatpak installation and …
=> feat: Ujust toggle updates for upcoming yafti replacement

system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
the issue is being worked on upstream since february see https://lore.kernel.org/all/20250227222411.3490595-1-seanjc@google.com/, however it seems to still be an issue so this will change the ujust to disable split lock detection which will cause looking-glass work properly.
=> fix(just): disable split_lock_detect when using kvmfr

system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Previous `:ro` was causing issues with Mangojuice, see https://github.com/radiolamp/mangojuice/issues/30
=> fix: Set flatpak global override for mangohud to writable

system_files/desktop/shared/usr/bin/bazzite-steam, system_files/desktop/shared/usr/bin/bazzite-steam-brand
This simple fix just moves `SYS_ID` to `bazzite-steam-brand`, since `SYS_ID` is simply not needed in `bazzite-steam` anymore, thanks to which a special startup is showing up for Steam Deck OLED again as before
=> fix(deck): show oled startup properly

system_files/desktop/silverblue/usr/share/ublue-os/just/90-bazzite-de.just
Looks like the `ujust restore-gnome-de-settings` was missing the shebang so it was running the script using sh rather than bash. This should fix #2577
=> chore: fixed restore-gnome-de-settings using sh instead of bash

.github/workflows/build_iso.yml
Fix ISO builds for F42: https://github.com/JasonN3/build-container-installer/releases/tag/v1.3.0
=> fix: update version to work with F42

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
When you do a ujust --choose the current documentation implies that LACT is just for AMD cards, when it supports, AMD, Nvidia and Intel GPUs
=> chore:docs: LACT supports more than AMD

system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
This fixes brew apps not being updated when launching the update recipe from a desktop shortcut
=> fix(just): Initialize brew into PATH in ujust update

.github/workflows/build.yml
Allows to make it easier to log the tags that are being pushed after build
=> ci: Add summary of image tags pushed to ghcr

system_files/desktop/shared/etc/systemd/system.conf.d/timeout.conf, system_files/desktop/shared/etc/systemd/user.conf.d/timeout.conf
The main systemd config requires the options to be set under the [Manager] section. without this the option is ignored and systemd logs a warning in the journal:
systemd[1]: /etc/systemd/system.conf.d/timeout.conf:1: Assignment outside of section. Ignoring.
Fixes: 3576341 ("chore: Move default timeout config to /etc for easy customization")
=> fix(desktop): correctly set DefaultTimeoutStopSec

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
mainly for those decky moments where everything is busted, this makes it easy to quickly uninstall, not just swap from release and pre-release.
=> feat: add uninstall option to Ujust setup-decky

.github/workflows/build.yml, system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-cdemu.just
Correct GUI_EDITION to match intended "Kinoite" value on non-gnome variants and install KDE6 packages.
=> fix(just): Identify GUI Edition using VARIANT

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-sunshine.just
add two new options to `ujust setup-sunshine`
- Open Portal: Launches users default browser to https://localhost:47990 to manage sunshine settings and add clients
- exit: easy exit option so user doesnt have to ctrl c
=> feat: add exit and open web portal opts to ujust setup-sunshine

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
This PR transforms the `bazzite-rollback-helper` tool into a comprehensive, interactive system that provides guided menu selections for listing images, rebasing, and rollbacks. The enhancement maintains full backward compatibility while adding ugum choose options and menus similar to other `ujust` commands.
=> feat: improve Bazzite-rebase-helper with interactive TUI

system_files/desktop/shared/usr/libexec/bazzite-yafti-launcher
Script /usr/libexec/bazzite-yafti-launcher pointing to ~/.local/bin/yafti-go (which doesn't exist) instead of /usr/bin/yafti-go
=> fix: bazzite-yafti-launcher pointing to non-existent file

system_files/desktop/shared/usr/lib/sysctl.d/75-networking.conf
Add this in config to get IPv6 temporary address.
See https://wiki.archlinux.org/title/IPv6#Privacy_extensions. There's no harm in adding it.
=> feat: Enable IPv6 privacy extensions

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just, system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
closes issue discussed in discord at: 
https://discordapp.com/channels/1072614816579063828/1386351838873387039/1386351838873387039
- Remove all sudo usage from get-decky-bazzite-buddy and get-framegen to prevent GUI freezes during YAFTI setup
- Add timeout protection (30s/60s) to prevent infinite hangs on network requests
- Fix plugin directory permissions using chmod instead of sudo
- Add script execution permissions for extracted .sh and .py files
=> fix: permission issues and hangs in decky ujusts

README.md
This will get this repo updated weekly, and it's pretty useful, adding it across the org to the big repos
=> docs: add deepwiki badge

system_files/nvidia/shared/usr/bin/dlss-swapper, system_files/nvidia/shared/usr/bin/dlss-swapper-dll
Adds CachyOS scripts ([1](https://github.com/CachyOS/CachyOS-Settings/blob/c60a32513719d8edc32182b739e501a9350c00e0/usr/bin/dlss-swapper)/[2](https://github.com/CachyOS/CachyOS-Settings/blob/c60a32513719d8edc32182b739e501a9350c00e0/usr/bin/dlss-swapper-dll)) to condense the launch command needed to update DLSS in proton games.
**from this:**
`PROTON_ENABLE_NGX_UPDATER=1 DXVK_NVAPI_DRS_SETTINGS=NGX_DLSS_SR_OVERRIDE=on,NGX_DLSS_RR_OVERRIDE=on,NGX_DLSS_FG_OVERRIDE=on,NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest,NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION=render_preset_latest %command%`
**to this:**
`dlss-swapper %command%`
------------------------------------------
`dlss-swapper %command%` - This forces Nvidia DLSS to use the latest preset for SR, RR and framegen + …
=> feat(nvidia): add CachyOS script to switch to latest dlss preset

system_files/desktop/shared/usr/lib/sysctl.d/75-networking.conf
Remove the sysctl configuration setting the default `qdisc` to `fq`. For general purpose computers, the default `fq_codel` is recommended over `fq`. The `fq` qdisc is more suited to TCP-heavy, high-bandwidth servers (https://www.bufferbloat.net/projects/codel/wiki/#Binary:~:text=net.core.default_qdisc,fq_codel%20for%20routers.).
The `fq` qdisc was likely set as this used to be a requirement for the `bbr` tcp congestion control algorithm that Bazzite uses, but this hasn't been the case since Linux kernel 4.20
(https://github.com/google/bbr/blob/master/Documentation/bbr-quick-start.md#obtain-kernel-sources-with-tcp-bbr).
Leaving this field unset will cause the system to use the systemd default, which is currently `fq_codel`.
=> feat: unset net.core.default_qdisc=fq sysctl

system_files/desktop/shared/usr/share/ublue-os/topgrade.toml
Makes topgrade only update the system (via rpm-ostree), flatpak, brew, fwupd, and the custom commands we set up.
All but system are marked as non-fatal for updates.
=> fix: Modify topgrade to only do a very limited subset of actions

Containerfile
This allows to use by default the bazaar wayland backend which doesn't work on nvidia + vulkan
Instead of forcing the x11 backend.
=> fix(bazaar): Run bazaar with the opengl backend

system_files/desktop/kinoite/etc/xdg/krunnerrc
This is the same as toggling the button in Plasma Search settings
related:
https://github.com/ublue-os/aurora/pull/585/commits/06d32d548ec726e03034a422c40ddf6d1851d357
=> fix: don't show discover search results

system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally rc71l_rc71l/wireplumber.conf.d/51-preferHDMI.conf, system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/51-preferHDMI.conf
Add headroom to the HDMI configs to prevent audio from cutting out.
=> fix(deck): Fix Ally / Ally X HDMI audio cutting out.

system_files/desktop/shared/usr/libexec/force-wol
The current script fails if there are multiple connected networks because $INTERFACE contains a string with all connected networks. Therefore I've changed the script to iterate all detected interfaces and enable wol for each of them.
=> fix: force-wol script can handle multiple network interfaces

system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just, system_files/desktop/shared/usr/share/yafti/yafti.yml
ujust to install lsfg-vk compat layer directly from PancakeTAS script, or pull latest decky plugin from my releases, with styled ugum choose TUI
also can exec each option directly, and added plugin to yafti for bazzite portal
=> feat: ujust for lsfg-vk and Lossless Scaling decky plugin install

Containerfile
fix bazaar crashes under VMs and low spec PCs
https://github.com/ublue-os/aurora/pull/713/
https://github.com/ublue-os/bluefin/pull/2794
feel free to move somewhere else in the file...
=> fix(pin): downgrade libdex to 0.9.1

system_files/desktop/silverblue/usr/share/applications/gamescope.desktop
While icon hints aren't currently supported by GNOME, we can still set a generic 'game' icon through a `.desktop` file with `NoDisplay=true`. See the Dash screenshots below:
=> fix: Add window icon for gamescope in GNOME

system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Fixed ujust-install-jetbrains-toolbox by copying script from Aurora.
Fixes: #3003
=> fix(desktop): fix ujust-install-jetbrains-toolbox script

.github/workflows/just-syntax-check.yml
With this action, all PRs and subsequent commits are subject to just syntax checks.
Fixes an issue where build action stops auto running after a few commits after PR is opened, and a PR could merge when subsequent commits break just syntax, causing testing / main branch builds to fail.
Now, this should prevent broken just syntax from merging in all cases.
=> chore: add just syntax check on PRs

system_files/desktop/shared/etc/default/steamos-nested-desktop, system_files/desktop/shared/etc/default/waydroid-launcher, system_files/desktop/shared/usr/libexec/bazzite-hardware-setup, system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware, system_files/desktop/shared/usr/libexec/hwsupport/needs-100-scale, system_files/desktop/shared/usr/libexec/hwsupport/needs-left-rotation
awaiting confirmation on sys_id in https://github.com/ublue-os/bazzite/issues/3002
=> fix: add zeenix handheld to rotation patch (fixes #3002)

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Refactors the `bazzite-rollback-helper` TUI to simplify the logic and adapt to some changes in the image matrix. 
Adds a warning when switching desktop environments (KDE to GNOME and vice-reversa), supports images 
with custom DEs from the template, list missing `-dx` images, and reduces overall complexity and lines of code.
=> fix: bazzite-rollback-helper TUI refactor

system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Remove old devnull placeholders at /etc/udev/rules.d that disabled old udev rules
=> chore: Remove leftovers of ublue-os-automount udev rules

system_files/desktop/silverblue/etc/systemd/user/sunshine.service.d/override.conf
I was trying bazzite-gnome and noticed the sunshine enable just script didn't seem to work. 
What I came to was that gnome doesn't trigger the systemd target that sunshine's service ships with (xdg-autostart-desktop). 
As others noted on #2044 a work-around is using Ignition, but that requires GUI access and for the user to figure out that the autostart thing is called Ignition and isn't in gnome settings etc. AND realize the just script hasn't worked.
This PR basically creates a unit override for the sunshine user service to specify that when its installed it should also be started when gnome-session.target is reached. This is done by the WantedBy systemd directive. I'm no expert but this seemed like the least-messy solution.
This is my first contribution to ublue, so I wasn't quite sure …
=> Fix(gnome): fix `ujust setup-sunshine enable` for gnome desktop

system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Some users can't rebase from one signed image to another lately, this simple fix resolves the problem with rollback helper.
=> fix(brh): fix rebasing from one signed image to another

system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
**Issue:**
The service `bazzite-hardware-setup` fails when updating kargs and internet access is required (updating metadata).
I'm using a vpn (mullvad) that blocks internet access on boot. In this scenario the fixup files are still written to `/etc/bazzite/fixups/**`.
Fixups files should only be written if kargs are successful.
**Fix:**
Collect commands the same way as the needed kargs and run them after applying kargs.
This won't fix the 'no internet' on boot issue but I think that's out of scope for this issue. It will work eventually when metadata gets updated.
The service could also have a trigger to run when the user session has started and if there is an active internet connection when it has failed on boot. `systemctl reboot` Would be inhibited by the user session.
=> fix(bazzite-hardware-setup): run fixups commands after applying kargs

system_files/desktop/shared/usr/bin/boot-windows
fixes #3015 
I don't think this would have any unintended side effects, but if so do let me know.
=> fix: return only one windows boot entry (fixes #3015)

system_files/deck/shared/usr/libexec/ublue-update-rebase
This file should only have one line containing the selected branch. When it appends and has multiple ones, the script reading from it has problems detecting the branch because it uses 'cat' but gets a lot of lines instead of just one string without newline.
Fixes #1543
=> fix: don't append /var/ublue-update/branch but overwrite it completey

system_files/desktop/shared/usr/share/ublue-os/bazaar/config.yaml
Only office does a better job than libre office at MS Word compatibility in my experience and it seems to be fairly commonly recommended + not so easy to discover for a new user. Seems like a good candidate to recommend as curated.
=> feat: recommend ONLYOFFICE in the Office & Productivity section of Bazaar

.github/workflows/generate_release.yml, Containerfile
It seems like there is no reason not to have both installed according to the [egl-wayland2](https://github.com/NVIDIA/egl-wayland2) project:
> This library can be installed alongside the previous egl-wayland implementation (https://github.com/NVIDIA/egl-wayland). The new library has a higher selection priority by default, so if both are present, then a 560 or later driver will select the new library, and an older driver will fall back to the old library.
I have tested this on my system both using `rpm-ostree install egl-wayland` and my custom image.
This resolves #3145 and possibly #3159.
So far I have not experienced any adverse effects from having both installed, but if anybody has a specific example of a reproducible egl-wayland2 improvement that I can use to test for regressions …
=> fix(nvidia): install egl-wayland alongside egl-wayland2

system_files/desktop/kinoite/usr/bin/kde-ptyxis
The original code in `system_files/desktop/kinoite/usr/bin/kde-ptyxis` replaced all occurrences of `-e` by `--`, which mangled legit paths, e.g. `/usr/bin/distrobox-enter` became `/usr/bin/distrobox--nter`.
After the fix, only standalone occurrences are replaced and all others are ignored.
=> fix: KDE menu entries created via distrobox-export do not work (#3163)

installer/titanoboa_hook_postrootfs.sh
That way we can pull `/tmp/anaconda.log` and `/tmp/anacoda_custom_logs/*` for logs in a more consistent way
=> chore(liveiso): Group kickstart logs into a single directory

.github/ISSUE_TEMPLATE/bug-report.yml, system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
from discord convo when troubleshooting: https://discord.com/channels/1072614816579063828/1087140957096517672/1415843918980841545
simple addition to `ujust get-logs` to also get rpm-ostree status output. 
Also copies it to clipboard for easy pasting into discord/github for troubleshooting
=> feat: add rpm-ostree status in ujust get-logs

system_files/nvidia/shared/usr/bin/bazzite-steam
This never worked properly, as I suppose it is initiated before the wayland session is live so `wl-copy` doesn't function.
=> fix(gamescope): rm gamemode clipboard feature

.github/workflows/changelog.py
Minor tweak to tag authors in GitHub release changelog. Nice way to credit each feature or fix (and also quickly get blame if something broke lol)
=> feat: add authors to gh release changelogs
